import Testing
import Foundation
import AISDDModels
@testable import AISDDEngine

/// Tests for the `SchemaCompiler` extraction (compile-schema slice). The headline is the correctness
/// anchor (`structuralReproducesCommitted`): compiling every real `.ai-sdd/schemas/*.schema.yaml`
/// must reproduce the committed `checks/<name>.structure.check.yaml` field-for-field. The rest are
/// per-tier units over hand-built `SchemaSpec`s (no IO).
struct SchemaCompilerTests {
    let loader = SpecLoader()

    /// The repo root (the package dir these tests run from), so the anchor can read the real
    /// committed schemas + checks.
    private var repoRoot: URL {
        // .../Tests/AISDDEngineTests/SchemaCompilerTests.swift → up 3 → package root.
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    // MARK: - A1/C5: correctness anchor

    /// Compile every committed schema and assert its structural check equals the committed
    /// `<name>.structure` check (name, checkKind, command, required), reading the real repo.
    @Test func structuralReproducesCommitted() throws {
        let home = repoRoot.appendingPathComponent(".ai-sdd", isDirectory: true)
        let schemasDir = home.appendingPathComponent("schemas", isDirectory: true)
        let checksDir = home.appendingPathComponent("checks", isDirectory: true)

        let schemaFiles = try FileManager.default.contentsOfDirectory(at: schemasDir, includingPropertiesForKeys: nil)
            .filter { $0.lastPathComponent.hasSuffix(".schema.yaml") }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
        #expect(!schemaFiles.isEmpty, "expected committed schemas to anchor against")

        for file in schemaFiles {
            let env = try loader.loadSchemaYAML(try String(contentsOf: file, encoding: .utf8))
            let name = env.metadata.name
            let compiled = try #require(
                SchemaCompiler.structuralCheck(env.spec, name: name, version: env.metadata.version ?? 1),
                "schema \(name) declares fields, expected a structural check")

            // Read the committed check beside it and compare the spec field-for-field.
            let committedURL = checksDir.appendingPathComponent("\(name).structure.check.yaml")
            let committed = try loader.loadCheckYAML(try String(contentsOf: committedURL, encoding: .utf8))

            #expect(compiled.name == committed.metadata.name)
            #expect(compiled.name == "\(name).structure")
            #expect(compiled.spec.checkKind == committed.spec.checkKind)
            #expect(compiled.spec.command == committed.spec.command)
            #expect(compiled.spec.required == committed.spec.required)
            #expect(compiled.origin == .autoGenerated)
        }
    }

    // MARK: - A2: structural template (pure, keyed off name/version/format)

    @Test func structuralTemplateKeyedOffNameVersionFormat() {
        let schema = SchemaSpec(format: "yaml", fields: ["x": FieldSpec(type: "string")])
        let check = SchemaCompiler.structuralCheck(schema, name: "demo", version: 2)
        #expect(check?.name == "demo.structure")
        #expect(check?.spec.checkKind == "deterministic")
        #expect(check?.spec.command ==
            "swift run ai-sdd check .ai-sdd/schemas/demo.schema.yaml .ai-sdd/artifacts/demo.v2.yaml")
        #expect(check?.spec.required == true)
        #expect(check?.origin == .autoGenerated)
    }

    @Test func formatDefaultsToYaml() {
        let schema = SchemaSpec(fields: ["x": FieldSpec(type: "string")])  // no format
        let check = SchemaCompiler.structuralCheck(schema, name: "demo", version: 1)
        #expect(check?.spec.command ==
            "swift run ai-sdd check .ai-sdd/schemas/demo.schema.yaml .ai-sdd/artifacts/demo.v1.yaml")
    }

    @Test func noFieldsYieldsNoStructuralCheck() {
        let schema = SchemaSpec(format: "yaml")  // no fields
        #expect(SchemaCompiler.structuralCheck(schema, name: "demo") == nil)
        #expect(SchemaCompiler.compile(schema, name: "demo").isEmpty)
    }

    // MARK: - A3: explicit-command rule (blocking / advisory)

    @Test func explicitCommandRuleBlocking() {
        let schema = SchemaSpec(rules: [RuleSpec(id: "build", command: "swift build")])  // severity omitted ⇒ blocking
        let checks = SchemaCompiler.compile(schema, name: "changeset")
        let rule = try? #require(checks.first { $0.name == "changeset.build" })
        #expect(rule?.spec.checkKind == "deterministic")
        #expect(rule?.spec.command == "swift build")
        #expect(rule?.spec.required == true)
        #expect(rule?.origin == .autoGenerated)
    }

    @Test func explicitCommandRuleAdvisory() {
        let schema = SchemaSpec(rules: [RuleSpec(id: "lint", command: "swiftlint", severity: "advisory")])
        let checks = SchemaCompiler.compile(schema, name: "changeset")
        let rule = checks.first { $0.name == "changeset.lint" }
        #expect(rule?.spec.command == "swiftlint")
        #expect(rule?.spec.required == false)
        #expect(rule?.origin == .autoGenerated)
    }

    // MARK: - A4: intent-only rule + judge → authored markers

    @Test func intentOnlyRuleIsAuthoredNoCommand() {
        let schema = SchemaSpec(rules: [RuleSpec(id: "scoped", intent: "changes ⊆ plan.files")])
        let checks = SchemaCompiler.compile(schema, name: "changeset")
        let rule = checks.first { $0.name == "changeset.scoped" }
        #expect(rule?.origin == .authored)
        #expect(rule?.spec.command == nil)        // never fabricate a command
        #expect(rule?.spec.required == false)
    }

    @Test func judgeIsAuthoredAdvisoryNoVerdict() {
        let schema = SchemaSpec(judge: [JudgeSpec(id: "plan-sound", rubric: "is the plan sound?")])
        let checks = SchemaCompiler.compile(schema, name: "feature-plan")
        let judge = checks.first { $0.name == "feature-plan.plan-sound" }
        #expect(judge?.origin == .authored)
        #expect(judge?.spec.checkKind == "judge")
        #expect(judge?.spec.required == false)
        #expect(judge?.spec.command == nil)       // never fabricate a verdict/command
    }

    // MARK: - tier ordering

    @Test func tiersEmitInOrderStructuralRulesJudges() {
        let schema = SchemaSpec(
            format: "yaml",
            fields: ["x": FieldSpec(type: "string")],
            rules: [RuleSpec(id: "build", command: "swift build")],
            judge: [JudgeSpec(id: "sound")])
        let checks = SchemaCompiler.compile(schema, name: "demo")
        #expect(checks.map(\.name) == ["demo.structure", "demo.build", "demo.sound"])
    }

    // MARK: - A7: YAML round-trip through the render edge

    @Test func renderedYamlRoundTrips() throws {
        let schema = SchemaSpec(format: "yaml", fields: ["x": FieldSpec(type: "string")])
        let check = try #require(SchemaCompiler.structuralCheck(schema, name: "demo"))
        let yaml = CompiledCheckRenderer.yaml(check)
        let env = try loader.loadCheckYAML(yaml)
        #expect(env.kind == "Check")
        #expect(env.metadata.name == check.name)
        #expect(env.spec == check.spec)
        #expect(yaml.contains("# origin: auto-generated"))
    }

    /// Additive decode: an existing schema with no `rules`/`judge` still decodes (A7), and a schema
    /// carrying them decodes their fields.
    @Test func rulesAndJudgeAreAdditive() throws {
        let bare = """
        apiVersion: ai-sdd/v1
        kind: Schema
        metadata: { name: bare, version: 1 }
        spec:
          format: yaml
          fields: { x: { type: string } }
        """
        let bareEnv = try loader.loadSchemaYAML(bare)
        #expect(bareEnv.spec.rules == nil)
        #expect(bareEnv.spec.judge == nil)

        let withTiers = """
        apiVersion: ai-sdd/v1
        kind: Schema
        metadata: { name: rich, version: 1 }
        spec:
          format: yaml
          fields: { x: { type: string } }
          rules:
            - { id: build, command: "swift build" }
            - { id: scoped, intent: "changes ⊆ plan.files", severity: advisory }
          judge:
            - { id: sound, rubric: "is it sound?" }
        """
        let env = try loader.loadSchemaYAML(withTiers)
        #expect(env.spec.rules?.count == 2)
        #expect(env.spec.rules?.first?.command == "swift build")
        #expect(env.spec.rules?.last?.isBlocking == false)
        #expect(env.spec.judge?.first?.rubric == "is it sound?")
    }

    // MARK: - Failure path: a malformed schema is rejected cleanly

    /// `ai-sdd compile` loads the schema before compiling. A not-well-formed schema must fail at that
    /// load boundary with the typed `SpecLoadError` (→ the CLI exits non-zero) — it never reaches the
    /// compiler and never yields a bogus check.
    @Test func malformedSchemaYAMLIsRejectedAtLoad() {
        let notWellFormed = """
        apiVersion: ai-sdd/v1
        kind: Schema
        metadata: { name: broken
        spec:
          format: yaml
          fields: { x: { type: string } }
        """  // unterminated flow mapping on the metadata line
        #expect(throws: SpecLoadError.self) {
            try loader.loadSchemaYAML(notWellFormed)
        }
    }

    /// Well-formed YAML that does not match the Schema shape (`fields` is a scalar, not a mapping) is
    /// a `.schema` load error — likewise caught before the compiler runs, not a crash or silent pass.
    @Test func schemaWithWrongShapeIsRejectedAtLoad() {
        let wrongShape = """
        apiVersion: ai-sdd/v1
        kind: Schema
        metadata: { name: bad-shape, version: 1 }
        spec:
          format: yaml
          fields: not-a-mapping
        """
        let thrown = #expect(throws: SpecLoadError.self) {
            try loader.loadSchemaYAML(wrongShape)
        }
        guard case .schema? = thrown else {
            Issue.record("expected SpecLoadError.schema, got \(String(describing: thrown))")
            return
        }
    }
}
