import Foundation
import AISDDModels

/// Renders a Pipeline as a Mermaid flowchart — the "renders 1:1 to the DAG diagram" view (§5,
/// ADR-0027). Pure: a deterministic transform of spec data, no I/O and no LLM, so it is testable
/// without a run and reproducible. Works for both kinds of DAG — a build pattern (artifact edges,
/// labelled with the Schema) and an orchestration graph (`depends_on` edges, no label).
public enum GraphRenderer {
    /// A fenced Mermaid `flowchart` block for the pipeline. Every node is declared (so isolated
    /// nodes still appear and labels are controlled); each edge renders an arrow, carrying its
    /// artifact Schema as the edge label unless it is absent or the `*` wildcard.
    public static func mermaid(_ pipeline: PipelineSpec, direction: String = "TD",
                               inheritedOwner: [String] = []) -> String {
        var lines = ["```mermaid", "flowchart \(direction)"]
        for node in pipeline.nodes {
            lines.append("    \(safeID(node.id))\(label(node, inheritedOwner: inheritedOwner))")
        }
        for edge in pipeline.edges {
            let schema = edge.artifact.flatMap { $0 == "*" ? nil : $0 }
            let arrow = schema.map { "-->|\($0)|" } ?? "-->"
            for from in edge.from.values {
                lines.append("    \(safeID(from)) \(arrow) \(safeID(edge.to))")
            }
        }
        lines.append("```")
        return lines.joined(separator: "\n")
    }

    /// One section of a project index: a heading and a pre-rendered body (a Mermaid block, or a
    /// note when a pipeline could not be loaded).
    public struct Section: Equatable, Sendable {
        public var heading: String
        public var body: String
        public init(heading: String, body: String) { self.heading = heading; self.body = body }
    }

    /// Assemble a single "single place, then drill down" index Markdown: a table of contents over
    /// the sections (the build pattern + one per feature), then each section's graph. One file that
    /// renders in any Markdown viewer; the TOC anchors are the drill-down.
    public static func projectIndex(title: String, sections: [Section]) -> String {
        var lines = ["# \(title) — project graph", "",
                     "_Generated by `ai-sdd graph --project` (ADR-0027). One place; the contents links drill down._", ""]
        if sections.count > 1 {
            lines.append("## Contents")
            for section in sections { lines.append("- [\(section.heading)](#\(anchor(section.heading)))") }
            lines.append("")
        }
        for section in sections {
            // An explicit anchor so the TOC link works regardless of the viewer's heading-slug rules.
            lines.append("<a id=\"\(anchor(section.heading))\"></a>")
            lines.append("## \(section.heading)")
            lines.append("")
            lines.append(section.body)
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    /// One milestone in a program graph: its name (a `correlation`) and the fragment sections that
    /// belong to it — the cross-repo join (ADR-0027), fragments grouped by milestone, not by repo.
    public struct Milestone: Equatable, Sendable {
        public var name: String
        public var fragments: [Section]
        public init(name: String, fragments: [Section]) { self.name = name; self.fragments = fragments }
    }

    /// Assemble the program (multi-repo) index: a table of contents over milestones, then each
    /// milestone with its fragments (H3) — the whole-program "single place, then drill down" view.
    public static func programIndex(title: String, milestones: [Milestone]) -> String {
        var lines = ["# \(title) — program graph", "",
                     "_Generated by `ai-sdd graph --plant` (ADR-0027). Fragments grouped by milestone, across repos._", ""]
        if milestones.count > 1 {
            lines.append("## Contents")
            for milestone in milestones { lines.append("- [\(milestone.name)](#\(anchor(milestone.name)))") }
            lines.append("")
        }
        for milestone in milestones {
            lines.append("<a id=\"\(anchor(milestone.name))\"></a>")
            lines.append("## \(milestone.name)")
            lines.append("")
            for fragment in milestone.fragments {
                lines.append("### \(fragment.heading)")
                lines.append("")
                lines.append(fragment.body)
                lines.append("")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// Wrap a generated Markdown doc into a self-contained HTML page — the "anyone-with-a-link"
    /// artifact (ADR-0027). One file, no server: it renders the Markdown and its Mermaid diagrams in
    /// the browser (marked + mermaid from a CDN). Truly-offline pre-rendered SVG would need a JS
    /// runtime the engine doesn't have, so this MVP renders client-side.
    public static func htmlPage(title: String, markdown: String) -> String {
        let safe = markdown.replacingOccurrences(of: "</script", with: "<\\/script")   // can't break out of the block
        return [
            "<!doctype html>",
            "<html lang=\"en\"><head><meta charset=\"utf-8\">",
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
            "<title>\(title) — ai-sdd graph</title>",
            "<style>",
            "  body{font-family:-apple-system,system-ui,sans-serif;max-width:980px;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#1f2328}",
            "  h2{border-bottom:1px solid #d0d7de;padding-bottom:.3em;margin-top:2rem}",
            "  code{background:#f6f8fa;padding:.15em .3em;border-radius:4px}",
            "  pre.mermaid{background:#f6f8fa;border-radius:6px;padding:1rem;text-align:center}",
            "  a{color:#0969da;text-decoration:none}",
            "</style></head><body>",
            "<div id=\"content\">Rendering…</div>",
            "<script type=\"text/markdown\" id=\"md\">",
            safe,
            "</script>",
            "<script src=\"https://cdn.jsdelivr.net/npm/marked/marked.min.js\"></script>",
            "<script type=\"module\">",
            "  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';",
            "  document.getElementById('content').innerHTML = marked.parse(document.getElementById('md').textContent);",
            "  document.querySelectorAll('code.language-mermaid').forEach(c => {",
            "    const pre = document.createElement('pre'); pre.className = 'mermaid';",
            "    pre.textContent = c.textContent; c.closest('pre').replaceWith(pre); });",
            "  mermaid.initialize({ startOnLoad: false }); await mermaid.run();",
            "</script></body></html>",
        ].joined(separator: "\n")
    }

    /// One prepared dashboard section. The renderer stays pure: callers load specs/runs and pass
    /// already-projected rows.
    public struct DashboardSection: Equatable, Sendable {
        public var heading: String
        public var projection: DashboardProjectionResult
        public var mermaid: String?
        // A single section-level freshness marker: true only when a run was attached BEST-EFFORT
        // (its recorded `pipelineDir` could not be reconciled by exact path, so it was matched by
        // trailing feature/program segment instead). Defaulted to false so existing `DashboardSection`
        // call sites and `Equatable` are unchanged; Part B's verdict band reuses this same flag.
        public var staleRun: Bool

        public init(heading: String, projection: DashboardProjectionResult, mermaid: String? = nil,
                    staleRun: Bool = false) {
            self.heading = heading
            self.projection = projection
            self.mermaid = mermaid
            self.staleRun = staleRun
        }
    }

    public static func dashboardMermaid(_ pipeline: PipelineSpec, rows: [DashboardProjectionRow],
                                        direction: String = "TD",
                                        inheritedOwner: [String] = []) -> String {
        let statuses = Dictionary(uniqueKeysWithValues: rows.map { ($0.node, $0.status) })
        let milestones = Dictionary(uniqueKeysWithValues: rows.map { ($0.node, $0.isMilestone) })
        var lines = ["flowchart \(direction)"]
        var milestoneStatuses: Set<DashboardStatus> = []
        for node in pipeline.nodes {
            let status = statuses[node.id] ?? .pending
            let labelBody = dashboardLabelBody(node, status: status, inheritedOwner: inheritedOwner)
            if milestones[node.id] == true {
                // A milestone/gate renders as a distinct hexagon gate shape (id{{"label"}}) with a
                // status-keyed milestone class so pass vs blocked still reads via the status color.
                milestoneStatuses.insert(status)
                lines.append("    \(safeID(node.id)){{\"\(labelBody)\"}}:::\(milestoneClass(status))")
            } else {
                lines.append("    \(safeID(node.id))[\"\(labelBody)\"]:::\(mermaidClass(status))")
            }
        }
        for edge in pipeline.edges {
            let schema = edge.artifact.flatMap { $0 == "*" ? nil : $0 }
            let arrow = schema.map { "-->|\(escapeMermaidLabel($0))|" } ?? "-->"
            for from in edge.from.values {
                lines.append("    \(safeID(from)) \(arrow) \(safeID(edge.to))")
            }
        }
        for status in DashboardStatus.allCases {
            let color = DashboardCharts.defaultColors[status] ?? "#9e9e9e"
            lines.append("    classDef \(mermaidClass(status)) fill:#ffffff,stroke:\(color),stroke-width:3px,color:#1f2328")
        }
        // Dedicated milestone classDefs (only for the statuses actually present), keyed off status so
        // a gate keeps its status color while reading as a gate: heavier stroke + tinted fill.
        for status in DashboardStatus.allCases where milestoneStatuses.contains(status) {
            let color = DashboardCharts.defaultColors[status] ?? "#9e9e9e"
            lines.append("    classDef \(milestoneClass(status)) fill:#f6f8fa,stroke:\(color),stroke-width:4px,color:#1f2328,stroke-dasharray:0")
        }
        return lines.joined(separator: "\n")
    }

    /// Render a self-contained dashboard page from prepared dashboard sections.
    ///
    /// `now` is INJECTED (defaulted at the call site, so existing callers stay source-stable). The
    /// function body reads no wall clock — given the same `sections` and `now` the output is
    /// byte-identical — which is why the verdict band's generation timestamp is pinnable in tests.
    /// The single wall-clock boundary is the Graph command, which reads `Date()` once and passes it.
    public static func dashboardPage(title: String, sections: [DashboardSection],
                                     now: Date = Date()) -> String {
        let summary = dashboardSummary(for: sections)
        let rows = sections.flatMap(\.projection.rows)
        let progress = progressPercent(done: summary.doneCount, total: summary.totalNodeCount)
        let progressWidth = String(format: "%.1f", progress)

        var parts = [
            "<!doctype html>",
            "<html lang=\"en\">",
            "<head>",
            "  <meta charset=\"utf-8\">",
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
            "  <title>\(escapeHTML(title)) — ai-sdd dashboard</title>",
            dashboardStyles(),
            "</head>",
            "<body>",
            "  <main class=\"dashboard-page\">",
            "    <header class=\"dashboard-header\">",
            "      <p class=\"dashboard-kicker\">ai-sdd project status</p>",
            "      <h1>\(escapeHTML(title))</h1>",
            "      <div class=\"summary-grid\" aria-label=\"Dashboard summary\">",
            "        <div><span class=\"summary-value\">\(summary.totalFeatureCount)</span><span class=\"summary-label\">features</span></div>",
            "        <div><span class=\"summary-value\">\(summary.totalNodeCount)</span><span class=\"summary-label\">slices</span></div>",
            "        <div><span class=\"summary-value\">\(summary.doneCount)/\(summary.totalNodeCount)</span><span class=\"summary-label\">done</span></div>",
            "        <div><span class=\"summary-value\">\(Int(progress.rounded()))%</span><span class=\"summary-label\">progress</span></div>",
            "      </div>",
            "      <div class=\"progress-wrap\" aria-label=\"\(escapeHTML("\(summary.doneCount) of \(summary.totalNodeCount) slices done"))\">",
            "        <div class=\"progress-track\" role=\"progressbar\" aria-valuemin=\"0\" aria-valuemax=\"100\" aria-valuenow=\"\(Int(progress.rounded()))\"><div class=\"progress-fill\" style=\"width: \(progressWidth)%\"></div></div>",
            "        <p>\(summary.doneCount)/\(summary.totalNodeCount) done</p>",
            "      </div>",
            "    </header>",
            "    \(statusLegend())",
            "    <section class=\"dashboard-charts\" aria-label=\"Dashboard charts\">",
            "      \(DashboardCharts.statusDonut(summary))",
            "      \(DashboardCharts.groupedBarChart(rows))",
            "    </section>",
            mermaidScript()
        ]
        // The whole-project rollup (verdict + portfolio bands) renders BEFORE any per-feature
        // detail, turning the flat scroll into an inverted pyramid (project first; features as
        // progressive disclosure). Both bands are a pure derivation over the already-assembled
        // sections — no new data source.
        parts.append(projectRollupHTML(sections: sections, now: now))
        for section in sections {
            parts.append(sectionHTML(section))
        }
        parts += [
            "  </main>",
            "</body>",
            "</html>"
        ]
        return parts.joined(separator: "\n")
    }

    /// A "Contracts" section listing each cross-repo contract — its provider + version and each
    /// consumer's requirement with a ✓ / ⚠ / ? compatibility mark (ADR-0027). nil when there are no
    /// contracts, so a program without them renders unchanged.
    public static func contractsSection(_ statuses: [Contracts.Status]) -> String? {
        guard !statuses.isEmpty else { return nil }
        var lines = ["## Contracts", "",
                     "_Cross-repo model-defining artifacts: provider version vs each consumer's range._", ""]
        for status in statuses {
            let provider = status.providedTag.map { "`\($0)` — \(status.provider ?? "?")" } ?? "⚠ no provider declared"
            lines.append("- **\(status.name)** · provider \(provider)")
            for consumer in status.consumers.sorted(by: { $0.fragment < $1.fragment }) {
                let mark = consumer.satisfied == nil ? "?" : (consumer.satisfied! ? "✓" : "⚠ skew")
                lines.append("    - \(mark) \(consumer.fragment) requires `\(consumer.range)`")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// A clean slug for an explicit anchor id: lowercase, alphanumerics kept, separators (space /
    /// hyphen / dropped punctuation like `·`) collapsed to a single `-`, with no leading/trailing `-`.
    static func anchor(_ heading: String) -> String {
        var out = ""
        var pendingSeparator = false
        for ch in heading.lowercased() {
            if ch.isLetter || ch.isNumber {
                if pendingSeparator && !out.isEmpty { out.append("-") }
                out.append(ch)
                pendingSeparator = false
            } else {
                pendingSeparator = true   // space, hyphen, or dropped punctuation → one separator
            }
        }
        return out
    }

    /// Mermaid node ids must be identifier-safe; non-identifier characters map to `_`. The original
    /// id is preserved in the visible label, so kebab-case ids read normally.
    private static func safeID(_ id: String) -> String {
        String(id.map { $0.isLetter || $0.isNumber || $0 == "_" ? $0 : "_" })
    }

    /// The visible node label: the id, plus a second line noting the worker, that it is a slice, its
    /// stack, and its owner — whatever the node declares (owner inherits the feature lead if unset).
    private static func label(_ node: PipelineNode, inheritedOwner: [String]) -> String {
        var detail: [String] = []
        if let worker = node.worker, worker != node.id { detail.append(worker) }   // skip if redundant
        if node.pipeline != nil { detail.append("slice") }
        if let stack = node.stack { detail.append("[\(stack)]") }
        let owner = node.owner ?? (inheritedOwner.isEmpty ? nil : inheritedOwner)
        if let owner, !owner.isEmpty { detail.append("@\(owner.joined(separator: ","))") }
        let second = detail.isEmpty ? "" : "<br/>\(detail.joined(separator: " "))"
        return "[\"\(node.id)\(second)\"]"
    }

    /// A one-line fragment header for the four tags (ADR-0027), or nil when none are set — so a plain
    /// pipeline renders unchanged. Goes above the graph in the rendered Markdown.
    public static func fragmentHeader(_ metadata: SpecMetadata) -> String? {
        var parts: [String] = []
        if let factory = metadata.factory { parts.append("**lane** \(factory)") }
        if let owner = metadata.owner, !owner.isEmpty { parts.append("**owner** \(owner.joined(separator: ", "))") }
        if let correlation = metadata.correlation { parts.append("**milestone** \(correlation)") }
        if let origin = metadata.origin, let text = originLabel(origin) { parts.append("**origin** \(text)") }
        return parts.isEmpty ? nil : parts.joined(separator: "  ·  ")
    }

    /// `repo@tag (hash) /path` — only the parts that are present.
    private static func originLabel(_ origin: Origin) -> String? {
        var text = origin.repo ?? ""
        if let tag = origin.tag { text += "@\(tag)" }
        if let hash = origin.hash { text += " (\(hash.prefix(8)))" }
        if let path = origin.path { text += text.isEmpty ? path : " \(path)" }
        let trimmed = text.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }

    private static func dashboardSummary(for sections: [DashboardSection]) -> DashboardProjectionSummary {
        var totals = Dictionary(uniqueKeysWithValues: DashboardStatus.allCases.map { ($0, 0) })
        var featureCount = 0
        var nodeCount = 0
        var doneCount = 0

        for section in sections {
            featureCount += max(0, section.projection.summary.totalFeatureCount)
            nodeCount += max(0, section.projection.summary.totalNodeCount)
            doneCount += max(0, section.projection.summary.doneCount)
            for status in DashboardStatus.allCases {
                totals[status, default: 0] += max(0, section.projection.summary.statusTotals[status, default: 0])
            }
        }

        return DashboardProjectionSummary(
            totalFeatureCount: featureCount,
            totalNodeCount: nodeCount,
            doneCount: doneCount,
            statusTotals: totals)
    }

    private static func progressPercent(done: Int, total: Int) -> Double {
        guard total > 0 else { return 0 }
        let percent = Double(done) / Double(total) * 100
        return min(100, max(0, percent))
    }

    private static func statusLegend() -> String {
        let items = DashboardStatus.allCases.map { status in
            "        <li><span class=\"legend-swatch status-\(escapeHTML(status.rawValue))\"></span>\(escapeHTML(status.rawValue))</li>"
        }.joined(separator: "\n")
        return [
            "    <nav class=\"status-legend\" aria-label=\"Status legend\">",
            "      <ul>",
            items,
            "      </ul>",
            "    </nav>"
        ].joined(separator: "\n")
    }

    // MARK: - Project rollup (verdict + portfolio bands)

    /// The one derived project trajectory. Escalation is the strongest signal and dominates rework
    /// (feature decision D4); velocity is explicitly deferred to the temporal slices and not read.
    public enum DashboardTrajectory: String, Equatable, Sendable {
        case onTrack = "on track"
        case slipping
        case stalled
    }

    /// Derive the project trajectory from the aggregated section rows ONLY (no new data source, no
    /// wall clock): `stalled` when any node is escalated, else `slipping` when any node is in rework,
    /// else `on track`. Pure and total over the section list.
    public static func dashboardTrajectory(for sections: [DashboardSection]) -> DashboardTrajectory {
        let statuses = sections.flatMap(\.projection.rows).map(\.status)
        if statuses.contains(.escalated) { return .stalled }
        if statuses.contains(.rework) { return .slipping }
        return .onTrack
    }

    /// One portfolio health row, derived purely from a section: status headline, slice-count %
    /// (labelled `slices`, not effort), owner (with `unowned` fallback), and the current blocker.
    public struct PortfolioRow: Equatable, Sendable {
        public var heading: String
        public var doneCount: Int
        public var totalCount: Int
        public var owner: String
        public var blocker: String
        public init(heading: String, doneCount: Int, totalCount: Int, owner: String, blocker: String) {
            self.heading = heading
            self.doneCount = doneCount
            self.totalCount = totalCount
            self.owner = owner
            self.blocker = blocker
        }
    }

    /// Derive one portfolio health row per section (pure, no I/O): the section summary supplies the
    /// `slices` count, the section's representative owner surfaces through the already-projected
    /// `row.owner` (falling back to the literal `unowned` when none is genuinely declared), and the
    /// current blocker is the worst escalated/rework node (or `—` when clear).
    public static func portfolioRows(for sections: [DashboardSection]) -> [PortfolioRow] {
        sections.map { section in
            PortfolioRow(
                heading: section.heading,
                doneCount: section.projection.summary.doneCount,
                totalCount: section.projection.summary.totalNodeCount,
                owner: portfolioOwner(for: section),
                blocker: portfolioBlocker(for: section))
        }
    }

    /// The integer slice-completion percent for a portfolio row (0 when a feature has no slices).
    static func slicePercent(done: Int, total: Int) -> Int {
        Int(progressPercent(done: done, total: total).rounded())
    }

    /// The representative owner for a feature's portfolio row. Reuses the owner already surfaced
    /// through `DashboardProjection.ownerLabel` on the section's rows; when no genuine owner is
    /// declared (the fallback degenerated to the feature/section name or empty), the cell renders the
    /// literal `unowned` so the gap is honest.
    private static func portfolioOwner(for section: DashboardSection) -> String {
        // The section heading is "Feature · <name>" / "Program · <name>" / "Build pattern · <name>";
        // its trailing segment is the feature name the owner fallback degenerates to.
        let featureName = section.heading.split(separator: "·").last.map {
            $0.trimmingCharacters(in: .whitespaces)
        } ?? section.heading
        let owners = section.projection.rows.map(\.owner)
            .filter { !$0.isEmpty && $0 != featureName }
        guard let owner = owners.first else { return "unowned" }
        return owner
    }

    /// The current blocker for a feature's portfolio row: the first escalated node, else the first
    /// rework node, else `—`. Mirrors the trajectory precedence (escalation dominates).
    private static func portfolioBlocker(for section: DashboardSection) -> String {
        let rows = section.projection.rows
        if let escalated = rows.first(where: { $0.status == .escalated }) { return escalated.node }
        if let rework = rows.first(where: { $0.status == .rework }) { return rework.node }
        return "—"
    }

    /// The whole-project rollup: a verdict band (trajectory + generation timestamp + freshness badge)
    /// and a portfolio band (one health row per feature), rendered before any per-feature detail.
    private static func projectRollupHTML(sections: [DashboardSection], now: Date) -> String {
        let trajectory = dashboardTrajectory(for: sections)
        let stale = sections.contains { $0.staleRun }
        // The freshness badge REUSES run-integrity's `⚠ stale run` marker — the single trust
        // mechanism — lit when any attached run is stale, and otherwise omitted.
        let freshnessBadge = stale
            ? "<span class=\"verdict-freshness stale\">\(escapeHTML("⚠ stale run"))</span>"
            : "<span class=\"verdict-freshness fresh\">fresh</span>"
        let verdict = [
            "    <section class=\"verdict-band\" aria-label=\"Project verdict\">",
            "      <span class=\"verdict-kicker\">verdict</span>",
            "      <p class=\"verdict-trajectory trajectory-\(trajectoryClass(trajectory))\">\(escapeHTML(trajectory.rawValue))</p>",
            "      <p class=\"verdict-meta\">",
            "        <span class=\"verdict-generated\">generated \(escapeHTML(formatTimestamp(now)))</span>",
            "        \(freshnessBadge)",
            "      </p>",
            "    </section>"
        ].joined(separator: "\n")

        let rows = portfolioRows(for: sections).map { row in
            let percent = slicePercent(done: row.doneCount, total: row.totalCount)
            return [
                "          <tr>",
                "            <td>\(escapeHTML(row.heading))</td>",
                "            <td>\(row.doneCount)/\(row.totalCount) (\(percent)%) slices</td>",
                "            <td>\(escapeHTML(row.owner))</td>",
                "            <td>\(escapeHTML(row.blocker))</td>",
                "          </tr>"
            ].joined(separator: "\n")
        }.joined(separator: "\n")
        let portfolioBody = rows.isEmpty ? "          <tr><td colspan=\"4\">No features</td></tr>" : rows
        let portfolio = [
            "    <section class=\"portfolio-band\" aria-label=\"Portfolio health\">",
            "      <h2>Portfolio</h2>",
            "      <table class=\"portfolio-table\">",
            "        <thead>",
            "          <tr><th>Feature</th><th>Slices</th><th>Owner</th><th>Blocker</th></tr>",
            "        </thead>",
            "        <tbody>",
            portfolioBody,
            "        </tbody>",
            "      </table>",
            "    </section>"
        ].joined(separator: "\n")

        return [verdict, portfolio].joined(separator: "\n")
    }

    private static func trajectoryClass(_ trajectory: DashboardTrajectory) -> String {
        switch trajectory {
        case .onTrack: return "on-track"
        case .slipping: return "slipping"
        case .stalled: return "stalled"
        }
    }

    /// A deterministic UTC timestamp for the verdict band, formatted purely from the injected `now`
    /// (no locale/time-zone wall-clock reads), so the same `now` always renders byte-identically.
    static func formatTimestamp(_ now: Date) -> String {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "UTC") ?? .gmt
        let c = calendar.dateComponents([.year, .month, .day, .hour, .minute], from: now)
        return String(format: "%04d-%02d-%02d %02d:%02d UTC",
                      c.year ?? 0, c.month ?? 0, c.day ?? 0, c.hour ?? 0, c.minute ?? 0)
    }

    private static func sectionHTML(_ section: DashboardSection) -> String {
        // A best-effort-attached (stale) run gets a single `⚠ stale run` marker in the header,
        // HTML-escaped like the heading. A healthy/healed exact-path match carries no marker.
        let staleMarker = section.staleRun
            ? "<span class=\"stale-run-marker\">\(escapeHTML("⚠ stale run"))</span>"
            : ""
        var parts = [
            "    <section class=\"dashboard-section\">",
            "      <header>",
            "        <h2>\(escapeHTML(section.heading))\(staleMarker)</h2>",
            "        <p>\(section.projection.summary.doneCount)/\(section.projection.summary.totalNodeCount) done</p>",
            "      </header>"
        ]
        if let mermaid = section.mermaid {
            parts.append(mermaidHTML(mermaid))
        } else {
            parts.append(graphHTML(rows: section.projection.rows))
        }
        parts += [
            tableHTML(rows: section.projection.rows),
            "    </section>"
        ]
        return parts.joined(separator: "\n")
    }

    private static func mermaidHTML(_ mermaid: String) -> String {
        [
            "      <div class=\"dashboard-mermaid-wrap\" aria-label=\"Dependency graph\">",
            "        <pre class=\"mermaid dashboard-mermaid\">",
            escapeHTML(mermaid),
            "        </pre>",
            "      </div>"
        ].joined(separator: "\n")
    }

    private static func graphHTML(rows: [DashboardProjectionRow]) -> String {
        let nodes = rows.map { row in
            [
                "          <li class=\"dashboard-node status-\(escapeHTML(row.status.rawValue))\" data-status=\"\(escapeHTML(row.status.rawValue))\">",
                "            <span class=\"node-id\">\(escapeHTML(row.node))</span>",
                "            <span class=\"node-status\">\(escapeHTML(row.status.rawValue))</span>",
                "          </li>"
            ].joined(separator: "\n")
        }.joined(separator: "\n")

        let edges = graphEdges(rows: rows).map { edge in
            "          <li><span>\(escapeHTML(edge.from))</span><span aria-hidden=\"true\">→</span><span>\(escapeHTML(edge.to))</span></li>"
        }.joined(separator: "\n")
        let edgeContent = edges.isEmpty ? "          <li>No dependencies</li>" : edges

        return [
            "      <div class=\"dashboard-graph\" aria-label=\"Section graph\">",
            "        <ol class=\"dashboard-nodes\">",
            nodes,
            "        </ol>",
            "        <ul class=\"dashboard-edges\">",
            edgeContent,
            "        </ul>",
            "      </div>"
        ].joined(separator: "\n")
    }

    private static func tableHTML(rows: [DashboardProjectionRow]) -> String {
        let body = rows.map { row in
            [
                "          <tr class=\"status-\(escapeHTML(row.status.rawValue))\">",
                "            <td>\(escapeHTML(row.node))</td>",
                "            <td>\(escapeHTML(row.status.rawValue))</td>",
                "            <td>\(escapeHTML(row.owner))</td>",
                "            <td>\(escapeHTML(row.stack ?? "—"))</td>",
                "            <td>\(escapeHTML(row.lane ?? "—"))</td>",
                "            <td>\(escapeHTML(row.milestone ?? "—"))</td>",
                "            <td>\(max(0, row.dependencyCount))</td>",
                "            <td>\(escapeHTML(row.nextActionHint.rawValue))</td>",
                "          </tr>"
            ].joined(separator: "\n")
        }.joined(separator: "\n")
        let rowsHTML = body.isEmpty ? "          <tr><td colspan=\"8\">No slices</td></tr>" : body

        return [
            "      <table class=\"slice-table\">",
            "        <thead>",
            "          <tr><th>Node</th><th>Status</th><th>Owner</th><th>Stack</th><th>Lane</th><th>Milestone</th><th>Dependencies</th><th>Next action</th></tr>",
            "        </thead>",
            "        <tbody>",
            rowsHTML,
            "        </tbody>",
            "      </table>"
        ].joined(separator: "\n")
    }

    private static func graphEdges(rows: [DashboardProjectionRow]) -> [(from: String, to: String)] {
        rows.enumerated().flatMap { index, row -> [(from: String, to: String)] in
            guard row.dependencyCount > 0, index > 0 else { return [] }
            let first = max(0, index - row.dependencyCount)
            return rows[first..<index].map { ($0.node, row.node) }
        }
    }

    private static func dashboardStyles() -> String {
        let variables = DashboardStatus.allCases.map { status in
            "    --status-\(status.rawValue): \(DashboardCharts.defaultColors[status] ?? "#9e9e9e");"
        }.joined(separator: "\n")
        return """
        <style>
        :root {
        \(variables)
          --text: #1f2328;
          --muted: #59636e;
          --line: #d0d7de;
          --panel: #f6f8fa;
          --background: #ffffff;
        }
        * { box-sizing: border-box; }
        body { margin: 0; background: var(--background); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.45; }
        .dashboard-page { max-width: 1180px; margin: 0 auto; padding: 32px 20px 48px; }
        .dashboard-header { border-bottom: 1px solid var(--line); padding-bottom: 24px; }
        .dashboard-kicker { color: var(--muted); font-size: 0.82rem; font-weight: 700; letter-spacing: 0; margin: 0 0 8px; text-transform: uppercase; }
        h1 { font-size: 2rem; margin: 0 0 20px; }
        h2 { font-size: 1.2rem; margin: 0; }
        .summary-grid { display: grid; gap: 12px; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); margin-bottom: 20px; }
        .summary-grid > div { border: 1px solid var(--line); border-radius: 8px; padding: 14px 16px; }
        .summary-value { display: block; font-size: 1.55rem; font-weight: 700; }
        .summary-label { color: var(--muted); font-size: 0.86rem; }
        .progress-wrap p { color: var(--muted); margin: 8px 0 0; }
        .progress-track { background: var(--panel); border: 1px solid var(--line); border-radius: 999px; height: 14px; overflow: hidden; }
        .progress-fill { background: var(--status-done); height: 100%; }
        .status-legend ul { display: flex; flex-wrap: wrap; gap: 10px 18px; justify-content: center; list-style: none; margin: 22px 0; padding: 0; }
        .status-legend li { align-items: center; color: var(--muted); display: flex; gap: 8px; font-size: 0.92rem; }
        .legend-swatch { border-radius: 999px; display: inline-block; height: 10px; width: 10px; }
        .dashboard-charts { align-items: start; display: grid; gap: 20px; grid-template-columns: minmax(0, 1fr); margin-bottom: 28px; }
        .dashboard-chart { max-width: 100%; }
        .dashboard-status-donut { justify-self: center; max-width: 360px; }
        .dashboard-grouped-bars { width: 100%; }
        .dashboard-section { border-top: 1px solid var(--line); padding: 26px 0; }
        .dashboard-section > header { align-items: baseline; display: flex; justify-content: space-between; gap: 16px; margin-bottom: 16px; }
        .dashboard-section > header p { color: var(--muted); margin: 0; }
        .stale-run-marker { color: var(--status-rework); font-size: 0.8rem; font-weight: 700; margin-left: 10px; white-space: nowrap; }
        .verdict-band { border: 1px solid var(--line); border-radius: 8px; margin: 24px 0 18px; padding: 18px 20px; }
        .verdict-kicker { color: var(--muted); font-size: 0.78rem; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; }
        .verdict-trajectory { font-size: 1.5rem; font-weight: 700; margin: 6px 0 10px; }
        .trajectory-on-track { color: var(--status-done); }
        .trajectory-slipping { color: var(--status-rework); }
        .trajectory-stalled { color: var(--status-escalated); }
        .verdict-meta { align-items: center; color: var(--muted); display: flex; flex-wrap: wrap; gap: 12px; margin: 0; }
        .verdict-freshness { font-size: 0.82rem; font-weight: 700; }
        .verdict-freshness.stale { color: var(--status-rework); }
        .verdict-freshness.fresh { color: var(--status-done); }
        .portfolio-band { margin: 0 0 28px; }
        .portfolio-band h2 { margin-bottom: 12px; }
        .portfolio-table { border-collapse: collapse; font-size: 0.92rem; width: 100%; }
        .portfolio-table th, .portfolio-table td { border-bottom: 1px solid var(--line); padding: 10px 8px; text-align: left; vertical-align: top; }
        .portfolio-table th { color: var(--muted); font-size: 0.78rem; text-transform: uppercase; }
        .dashboard-mermaid-wrap { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; margin-bottom: 18px; overflow-x: auto; padding: 16px; }
        .dashboard-mermaid { margin: 0; min-width: 640px; text-align: center; }
        .dashboard-graph { display: grid; gap: 16px; grid-template-columns: minmax(0, 1fr) minmax(220px, 0.45fr); margin-bottom: 18px; }
        .dashboard-nodes { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); list-style: none; margin: 0; padding: 0; }
        .dashboard-node { border: 1px solid var(--line); border-left: 5px solid currentColor; border-radius: 8px; color: var(--muted); min-height: 70px; padding: 12px; }
        .node-id { color: var(--text); display: block; font-weight: 700; overflow-wrap: anywhere; }
        .node-status { display: block; font-size: 0.82rem; margin-top: 6px; }
        .dashboard-edges { background: var(--panel); border-radius: 8px; list-style: none; margin: 0; padding: 12px; }
        .dashboard-edges li { align-items: center; display: flex; gap: 8px; min-height: 26px; overflow-wrap: anywhere; }
        .slice-table { border-collapse: collapse; font-size: 0.92rem; width: 100%; }
        .slice-table th, .slice-table td { border-bottom: 1px solid var(--line); padding: 10px 8px; text-align: left; vertical-align: top; }
        .slice-table th { color: var(--muted); font-size: 0.78rem; text-transform: uppercase; }
        .status-done { color: var(--status-done); }
        .status-in-progress { color: var(--status-in-progress); }
        .status-rework { color: var(--status-rework); }
        .status-escalated { color: var(--status-escalated); }
        .status-runnable { color: var(--status-runnable); }
        .status-pending { color: var(--status-pending); }
        .legend-swatch.status-done { background: var(--status-done); }
        .legend-swatch.status-in-progress { background: var(--status-in-progress); }
        .legend-swatch.status-rework { background: var(--status-rework); }
        .legend-swatch.status-escalated { background: var(--status-escalated); }
        .legend-swatch.status-runnable { background: var(--status-runnable); }
        .legend-swatch.status-pending { background: var(--status-pending); }
        @media (max-width: 760px) {
          .dashboard-graph { grid-template-columns: 1fr; }
          .slice-table { display: block; overflow-x: auto; }
        }
        </style>
        """
    }

    private static func mermaidScript() -> String {
        [
            "    <script type=\"module\">",
            "      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';",
            "      mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });",
            "      await mermaid.run({ querySelector: '.dashboard-mermaid' });",
            "    </script>"
        ].joined(separator: "\n")
    }

    /// The escaped inner label content (id + a detail line), without the node-shape brackets — so a
    /// caller can wrap it in `["…"]` (feature/plain) or `{{"…"}}` (milestone gate). Every dynamic
    /// value is escaped via `escapeMermaidLabel`.
    private static func dashboardLabelBody(_ node: PipelineNode, status: DashboardStatus,
                                           inheritedOwner: [String]) -> String {
        var detail = [status.rawValue]
        if let worker = node.worker, worker != node.id { detail.append(worker) }
        if node.pipeline != nil { detail.append("slice") }
        if let stack = node.stack { detail.append("[\(stack)]") }
        let owner = node.owner ?? (inheritedOwner.isEmpty ? nil : inheritedOwner)
        if let owner, !owner.isEmpty { detail.append("@\(owner.joined(separator: ","))") }
        return "\(escapeMermaidLabel(node.id))<br/>\(escapeMermaidLabel(detail.joined(separator: " ")))"
    }

    private static func mermaidClass(_ status: DashboardStatus) -> String {
        "status_\(status.rawValue.replacingOccurrences(of: "-", with: "_"))"
    }

    /// The dedicated milestone/gate class for a status (`milestone_<status>`), distinct from the
    /// feature/plain `status_<status>` class so a gate is styled as a gate while still color-keyed
    /// off its status (pass vs blocked).
    private static func milestoneClass(_ status: DashboardStatus) -> String {
        "milestone_\(status.rawValue.replacingOccurrences(of: "-", with: "_"))"
    }

    private static func escapeMermaidLabel(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private static func escapeHTML(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }
}
