import Foundation
import AISDDModels

/// Renders a Pipeline as a Mermaid flowchart — the "renders 1:1 to the DAG diagram" view (§5,
/// ADR-0027). Pure: a deterministic transform of spec data, no I/O and no LLM, so it is testable
/// without a run and reproducible. Works for both kinds of DAG — a build pattern (artifact edges,
/// labelled with the Schema) and an orchestration graph (`depends_on` edges, no label).
public enum GraphRenderer {
    /// A fenced Mermaid `flowchart` block for the pipeline. Every node is declared (so isolated
    /// nodes still appear and labels are controlled); each edge renders an arrow, carrying its
    /// artifact Schema as the edge label unless it is absent or the `*` wildcard.
    public static func mermaid(_ pipeline: PipelineSpec, direction: String = "TD",
                               inheritedOwner: [String] = []) -> String {
        var lines = ["```mermaid", "flowchart \(direction)"]
        for node in pipeline.nodes {
            lines.append("    \(safeID(node.id))\(label(node, inheritedOwner: inheritedOwner))")
        }
        for edge in pipeline.edges {
            let schema = edge.artifact.flatMap { $0 == "*" ? nil : $0 }
            let arrow = schema.map { "-->|\($0)|" } ?? "-->"
            for from in edge.from.values {
                lines.append("    \(safeID(from)) \(arrow) \(safeID(edge.to))")
            }
        }
        lines.append("```")
        return lines.joined(separator: "\n")
    }

    /// One section of a project index: a heading and a pre-rendered body (a Mermaid block, or a
    /// note when a pipeline could not be loaded).
    public struct Section: Equatable, Sendable {
        public var heading: String
        public var body: String
        public init(heading: String, body: String) { self.heading = heading; self.body = body }
    }

    /// Assemble a single "single place, then drill down" index Markdown: a table of contents over
    /// the sections (the build pattern + one per feature), then each section's graph. One file that
    /// renders in any Markdown viewer; the TOC anchors are the drill-down.
    public static func projectIndex(title: String, sections: [Section]) -> String {
        var lines = ["# \(title) — project graph", "",
                     "_Generated by `ai-sdd graph --project` (ADR-0027). One place; the contents links drill down._", ""]
        if sections.count > 1 {
            lines.append("## Contents")
            for section in sections { lines.append("- [\(section.heading)](#\(anchor(section.heading)))") }
            lines.append("")
        }
        for section in sections {
            // An explicit anchor so the TOC link works regardless of the viewer's heading-slug rules.
            lines.append("<a id=\"\(anchor(section.heading))\"></a>")
            lines.append("## \(section.heading)")
            lines.append("")
            lines.append(section.body)
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    /// One milestone in a program graph: its name (a `correlation`) and the fragment sections that
    /// belong to it — the cross-repo join (ADR-0027), fragments grouped by milestone, not by repo.
    public struct Milestone: Equatable, Sendable {
        public var name: String
        public var fragments: [Section]
        public init(name: String, fragments: [Section]) { self.name = name; self.fragments = fragments }
    }

    /// Assemble the program (multi-repo) index: a table of contents over milestones, then each
    /// milestone with its fragments (H3) — the whole-program "single place, then drill down" view.
    public static func programIndex(title: String, milestones: [Milestone]) -> String {
        var lines = ["# \(title) — program graph", "",
                     "_Generated by `ai-sdd graph --plant` (ADR-0027). Fragments grouped by milestone, across repos._", ""]
        if milestones.count > 1 {
            lines.append("## Contents")
            for milestone in milestones { lines.append("- [\(milestone.name)](#\(anchor(milestone.name)))") }
            lines.append("")
        }
        for milestone in milestones {
            lines.append("<a id=\"\(anchor(milestone.name))\"></a>")
            lines.append("## \(milestone.name)")
            lines.append("")
            for fragment in milestone.fragments {
                lines.append("### \(fragment.heading)")
                lines.append("")
                lines.append(fragment.body)
                lines.append("")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// Wrap a generated Markdown doc into a self-contained HTML page — the "anyone-with-a-link"
    /// artifact (ADR-0027). One file, no server: it renders the Markdown and its Mermaid diagrams in
    /// the browser (marked + mermaid from a CDN). Truly-offline pre-rendered SVG would need a JS
    /// runtime the engine doesn't have, so this MVP renders client-side.
    public static func htmlPage(title: String, markdown: String) -> String {
        let safe = markdown.replacingOccurrences(of: "</script", with: "<\\/script")   // can't break out of the block
        return [
            "<!doctype html>",
            "<html lang=\"en\"><head><meta charset=\"utf-8\">",
            "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
            "<title>\(title) — ai-sdd graph</title>",
            "<style>",
            "  body{font-family:-apple-system,system-ui,sans-serif;max-width:980px;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#1f2328}",
            "  h2{border-bottom:1px solid #d0d7de;padding-bottom:.3em;margin-top:2rem}",
            "  code{background:#f6f8fa;padding:.15em .3em;border-radius:4px}",
            "  pre.mermaid{background:#f6f8fa;border-radius:6px;padding:1rem;text-align:center}",
            "  a{color:#0969da;text-decoration:none}",
            "</style></head><body>",
            "<div id=\"content\">Rendering…</div>",
            "<script type=\"text/markdown\" id=\"md\">",
            safe,
            "</script>",
            "<script src=\"https://cdn.jsdelivr.net/npm/marked/marked.min.js\"></script>",
            "<script type=\"module\">",
            "  import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';",
            "  document.getElementById('content').innerHTML = marked.parse(document.getElementById('md').textContent);",
            "  document.querySelectorAll('code.language-mermaid').forEach(c => {",
            "    const pre = document.createElement('pre'); pre.className = 'mermaid';",
            "    pre.textContent = c.textContent; c.closest('pre').replaceWith(pre); });",
            "  mermaid.initialize({ startOnLoad: false }); await mermaid.run();",
            "</script></body></html>",
        ].joined(separator: "\n")
    }

    /// One prepared dashboard section. The renderer stays pure: callers load specs/runs and pass
    /// already-projected rows.
    public struct DashboardSection: Equatable, Sendable {
        public var heading: String
        public var projection: DashboardProjectionResult
        public var mermaid: String?
        // A single section-level freshness marker: true only when a run was attached BEST-EFFORT
        // (its recorded `pipelineDir` could not be reconciled by exact path, so it was matched by
        // trailing feature/program segment instead). Defaulted to false so existing `DashboardSection`
        // call sites and `Equatable` are unchanged; Part B's verdict band reuses this same flag.
        public var staleRun: Bool
        // The section's runnable slices ranked by transitive downstream-unblock count, as computed by
        // `DashboardCriticalPath.runnableRanking` from the section's spec + folded state. The assemblers
        // (where spec/state live) populate it; the renderer reads it without recomputation so it stays
        // pure. Defaulted to [] — mirroring how `staleRun` was added — so existing `DashboardSection`
        // call sites and `Equatable` are source-stable, and a section with no ranking simply contributes
        // no unblockers to the attention band.
        public var runnableRanking: [RankedRunnable]
        // The feature's master-requirements DEFINITION — the `## Goal` body of its requirements.md,
        // read and extracted by `ProjectDashboardAssembler` (the file-aware boundary) and threaded
        // here so the renderer stays pure. Defaulted to nil — mirroring how `staleRun` and
        // `runnableRanking` were added — so existing `DashboardSection` call sites and `Equatable`
        // are source-stable; nil ⇒ no definition pane (graceful degradation when requirements.md is
        // absent/unreadable/has no Goal).
        public var requirementsDefinition: String?
        // The critical-path node ids (`DashboardCriticalPath.criticalPath` over this section's spec),
        // populated by the assemblers where the spec lives so the renderer marks those nodes without
        // recomputing. Defaulted to [] so existing call sites and `Equatable` stay source-stable; an
        // empty set marks nothing.
        public var criticalPathNodes: Set<String>
        // The matched run's persisted records (`RunStore.eventsWithMetadata`), threaded by the
        // assemblers (the file-aware boundary) so Part B's pure temporal metrics — cycle time, WIP
        // age, velocity — read the same run the projection does WITHOUT the renderer touching the
        // store or the wall clock. Defaulted to [] — mirroring how `staleRun`/`runnableRanking` were
        // added — so existing `DashboardSection` call sites and `Equatable` stay source-stable; an
        // empty list (or one with no timestamped `at`s) makes every temporal metric self-suppress.
        public var runEvents: [RunEventRecord]

        public init(heading: String, projection: DashboardProjectionResult, mermaid: String? = nil,
                    staleRun: Bool = false, runnableRanking: [RankedRunnable] = [],
                    requirementsDefinition: String? = nil, criticalPathNodes: Set<String> = [],
                    runEvents: [RunEventRecord] = []) {
            self.heading = heading
            self.projection = projection
            self.mermaid = mermaid
            self.staleRun = staleRun
            self.runnableRanking = runnableRanking
            self.requirementsDefinition = requirementsDefinition
            self.criticalPathNodes = criticalPathNodes
            self.runEvents = runEvents
        }
    }

    /// `criticalPath` is the threaded set of critical-path node ids (from
    /// `DashboardCriticalPath.criticalPath`, populated by the assemblers); nodes in it carry an extra
    /// `critical_path` class — applied via a SEPARATE `class <id,...> critical_path` statement, since
    /// mermaid's `:::` shorthand takes only ONE class per node — so the longest dependency chain is
    /// visibly marked while each node keeps its status color. Defaulted to `[]` so existing call sites
    /// stay source-stable and an empty set marks nothing.
    public static func dashboardMermaid(_ pipeline: PipelineSpec, rows: [DashboardProjectionRow],
                                        direction: String = "TD",
                                        inheritedOwner: [String] = [],
                                        criticalPath: Set<String> = []) -> String {
        let statuses = Dictionary(uniqueKeysWithValues: rows.map { ($0.node, $0.status) })
        let milestones = Dictionary(uniqueKeysWithValues: rows.map { ($0.node, $0.isMilestone) })
        var lines = ["flowchart \(direction)"]
        var milestoneStatuses: Set<DashboardStatus> = []
        // The safe ids of nodes on the critical path, collected so the extra `critical_path` class is
        // applied via SEPARATE `class <id,...> critical_path` statements. The `:::` shorthand accepts
        // only ONE class per node — chaining a second `:::` is a mermaid grammar error — so the node
        // keeps its status/milestone class as `:::status_*`/`:::milestone_*` and the critical-path
        // class is layered on with mermaid's multi-class `class` form.
        var criticalSafeIDs: [String] = []
        for node in pipeline.nodes {
            let status = statuses[node.id] ?? .pending
            let labelBody = dashboardLabelBody(node, status: status, inheritedOwner: inheritedOwner)
            if criticalPath.contains(node.id) { criticalSafeIDs.append(safeID(node.id)) }
            if milestones[node.id] == true {
                // A milestone/gate renders as a distinct hexagon gate shape (id{{"label"}}) with a
                // status-keyed milestone class so pass vs blocked still reads via the status color.
                milestoneStatuses.insert(status)
                lines.append("    \(safeID(node.id)){{\"\(labelBody)\"}}:::\(milestoneClass(status))")
            } else {
                lines.append("    \(safeID(node.id))[\"\(labelBody)\"]:::\(mermaidClass(status))")
            }
        }
        for edge in pipeline.edges {
            let schema = edge.artifact.flatMap { $0 == "*" ? nil : $0 }
            let arrow = schema.map { "-->|\(escapeMermaidLabel($0))|" } ?? "-->"
            for from in edge.from.values {
                lines.append("    \(safeID(from)) \(arrow) \(safeID(edge.to))")
            }
        }
        for status in DashboardStatus.allCases {
            let color = DashboardCharts.defaultColors[status] ?? "#9e9e9e"
            lines.append("    classDef \(mermaidClass(status)) fill:#ffffff,stroke:\(color),stroke-width:3px,color:#1f2328")
        }
        // Dedicated milestone classDefs (only for the statuses actually present), keyed off status so
        // a gate keeps its status color while reading as a gate: heavier stroke + tinted fill.
        for status in DashboardStatus.allCases where milestoneStatuses.contains(status) {
            let color = DashboardCharts.defaultColors[status] ?? "#9e9e9e"
            lines.append("    classDef \(milestoneClass(status)) fill:#f6f8fa,stroke:\(color),stroke-width:4px,color:#1f2328,stroke-dasharray:0")
        }
        // A single critical-path classDef (only when at least one node is on the path): a distinct
        // amber edge-tinted marker layered over the per-status class so the chain reads at a glance
        // while each node keeps its status color via its first class. The class is applied via a
        // SEPARATE `class a,b,c critical_path` statement (mermaid's multi-class form) rather than a
        // chained second `:::`, which mermaid rejects as a grammar error.
        if !criticalSafeIDs.isEmpty {
            lines.append("    classDef \(criticalPathClass) stroke:#d97706,stroke-width:4px,stroke-dasharray:6 3")
            lines.append("    class \(criticalSafeIDs.joined(separator: ",")) \(criticalPathClass)")
        }
        return lines.joined(separator: "\n")
    }

    /// Render a self-contained dashboard page from prepared dashboard sections.
    ///
    /// `now` is INJECTED (defaulted at the call site, so existing callers stay source-stable). The
    /// function body reads no wall clock — given the same `sections` and `now` the output is
    /// byte-identical — which is why the verdict band's generation timestamp is pinnable in tests.
    /// The single wall-clock boundary is the Graph command, which reads `Date()` once and passes it.
    public static func dashboardPage(title: String, sections: [DashboardSection],
                                     now: Date = Date()) -> String {
        let summary = dashboardSummary(for: sections)
        let progress = progressPercent(done: summary.doneCount, total: summary.totalNodeCount)
        let progressWidth = String(format: "%.1f", progress)

        var parts = [
            "<!doctype html>",
            "<html lang=\"en\">",
            "<head>",
            "  <meta charset=\"utf-8\">",
            "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
            "  <title>\(escapeHTML(title)) — ai-sdd dashboard</title>",
            dashboardStyles(),
            "</head>",
            "<body>",
            "  <main class=\"dashboard-page\">",
            "    <header class=\"dashboard-header\">",
            "      <p class=\"dashboard-kicker\">ai-sdd project status</p>",
            "      <h1>\(escapeHTML(title))</h1>",
            "      <div class=\"summary-grid\" aria-label=\"Dashboard summary\">",
            "        <div><span class=\"summary-value\">\(summary.totalFeatureCount)</span><span class=\"summary-label\">features</span></div>",
            "        <div><span class=\"summary-value\">\(summary.totalNodeCount)</span><span class=\"summary-label\">slices</span></div>",
            "        <div><span class=\"summary-value\">\(summary.doneCount)/\(summary.totalNodeCount)</span><span class=\"summary-label\">done</span></div>",
            "        <div><span class=\"summary-value\">\(Int(progress.rounded()))%</span><span class=\"summary-label\">progress</span></div>",
            "      </div>",
            "      <div class=\"progress-wrap\" aria-label=\"\(escapeHTML("\(summary.doneCount) of \(summary.totalNodeCount) slices done"))\">",
            "        <div class=\"progress-track\" role=\"progressbar\" aria-valuemin=\"0\" aria-valuemax=\"100\" aria-valuenow=\"\(Int(progress.rounded()))\"><div class=\"progress-fill\" style=\"width: \(progressWidth)%\"></div></div>",
            "        <p>\(summary.doneCount)/\(summary.totalNodeCount) done</p>",
            "      </div>",
            "    </header>",
            "    \(statusLegend())",
            "    <section class=\"dashboard-charts\" aria-label=\"Dashboard charts\">",
            "      \(DashboardCharts.statusDonut(summary))",
            "      \(DashboardCharts.groupedBarChart(ownerLoadGroups(for: sections), title: "Load by owner"))",
            "      \(DashboardCharts.groupedBarChart(featureProgressGroups(for: sections), title: "Progress by feature"))",
            "    </section>",
            mermaidScript()
        ]
        // The whole-project rollup (verdict + portfolio bands) renders BEFORE any per-feature
        // detail, turning the flat scroll into an inverted pyramid (project first; features as
        // progressive disclosure). Both bands are a pure derivation over the already-assembled
        // sections — no new data source.
        parts.append(projectRollupHTML(sections: sections, now: now))
        for section in sections {
            parts.append(sectionHTML(section))
        }
        parts += [
            "  </main>",
            "</body>",
            "</html>"
        ]
        return parts.joined(separator: "\n")
    }

    /// A "Contracts" section listing each cross-repo contract — its provider + version and each
    /// consumer's requirement with a ✓ / ⚠ / ? compatibility mark (ADR-0027). nil when there are no
    /// contracts, so a program without them renders unchanged.
    public static func contractsSection(_ statuses: [Contracts.Status]) -> String? {
        guard !statuses.isEmpty else { return nil }
        var lines = ["## Contracts", "",
                     "_Cross-repo model-defining artifacts: provider version vs each consumer's range._", ""]
        for status in statuses {
            let provider = status.providedTag.map { "`\($0)` — \(status.provider ?? "?")" } ?? "⚠ no provider declared"
            lines.append("- **\(status.name)** · provider \(provider)")
            for consumer in status.consumers.sorted(by: { $0.fragment < $1.fragment }) {
                let mark = consumer.satisfied == nil ? "?" : (consumer.satisfied! ? "✓" : "⚠ skew")
                lines.append("    - \(mark) \(consumer.fragment) requires `\(consumer.range)`")
            }
        }
        return lines.joined(separator: "\n")
    }

    /// A clean slug for an explicit anchor id: lowercase, alphanumerics kept, separators (space /
    /// hyphen / dropped punctuation like `·`) collapsed to a single `-`, with no leading/trailing `-`.
    static func anchor(_ heading: String) -> String {
        var out = ""
        var pendingSeparator = false
        for ch in heading.lowercased() {
            if ch.isLetter || ch.isNumber {
                if pendingSeparator && !out.isEmpty { out.append("-") }
                out.append(ch)
                pendingSeparator = false
            } else {
                pendingSeparator = true   // space, hyphen, or dropped punctuation → one separator
            }
        }
        return out
    }

    /// Mermaid node ids must be identifier-safe; non-identifier characters map to `_`. The original
    /// id is preserved in the visible label, so kebab-case ids read normally.
    private static func safeID(_ id: String) -> String {
        String(id.map { $0.isLetter || $0.isNumber || $0 == "_" ? $0 : "_" })
    }

    /// The visible node label: the id, plus a second line noting the worker, that it is a slice, its
    /// stack, and its owner — whatever the node declares (owner inherits the feature lead if unset).
    private static func label(_ node: PipelineNode, inheritedOwner: [String]) -> String {
        var detail: [String] = []
        if let worker = node.worker, worker != node.id { detail.append(worker) }   // skip if redundant
        if node.pipeline != nil { detail.append("slice") }
        if let stack = node.stack { detail.append("[\(stack)]") }
        let owner = node.owner ?? (inheritedOwner.isEmpty ? nil : inheritedOwner)
        if let owner, !owner.isEmpty { detail.append("@\(owner.joined(separator: ","))") }
        let second = detail.isEmpty ? "" : "<br/>\(detail.joined(separator: " "))"
        return "[\"\(node.id)\(second)\"]"
    }

    /// A one-line fragment header for the four tags (ADR-0027), or nil when none are set — so a plain
    /// pipeline renders unchanged. Goes above the graph in the rendered Markdown.
    public static func fragmentHeader(_ metadata: SpecMetadata) -> String? {
        var parts: [String] = []
        if let factory = metadata.factory { parts.append("**lane** \(factory)") }
        if let owner = metadata.owner, !owner.isEmpty { parts.append("**owner** \(owner.joined(separator: ", "))") }
        if let correlation = metadata.correlation { parts.append("**milestone** \(correlation)") }
        if let origin = metadata.origin, let text = originLabel(origin) { parts.append("**origin** \(text)") }
        return parts.isEmpty ? nil : parts.joined(separator: "  ·  ")
    }

    /// `repo@tag (hash) /path` — only the parts that are present.
    private static func originLabel(_ origin: Origin) -> String? {
        var text = origin.repo ?? ""
        if let tag = origin.tag { text += "@\(tag)" }
        if let hash = origin.hash { text += " (\(hash.prefix(8)))" }
        if let path = origin.path { text += text.isEmpty ? path : " \(path)" }
        let trimmed = text.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }

    private static func dashboardSummary(for sections: [DashboardSection]) -> DashboardProjectionSummary {
        var totals = Dictionary(uniqueKeysWithValues: DashboardStatus.allCases.map { ($0, 0) })
        var featureCount = 0
        var nodeCount = 0
        var doneCount = 0

        for section in sections {
            featureCount += max(0, section.projection.summary.totalFeatureCount)
            nodeCount += max(0, section.projection.summary.totalNodeCount)
            doneCount += max(0, section.projection.summary.doneCount)
            for status in DashboardStatus.allCases {
                totals[status, default: 0] += max(0, section.projection.summary.statusTotals[status, default: 0])
            }
        }

        return DashboardProjectionSummary(
            totalFeatureCount: featureCount,
            totalNodeCount: nodeCount,
            doneCount: doneCount,
            statusTotals: totals)
    }

    private static func progressPercent(done: Int, total: Int) -> Double {
        guard total > 0 else { return 0 }
        let percent = Double(done) / Double(total) * 100
        return min(100, max(0, percent))
    }

    private static func statusLegend() -> String {
        let items = DashboardStatus.allCases.map { status in
            "        <li><span class=\"legend-swatch status-\(escapeHTML(status.rawValue))\"></span>\(escapeHTML(status.rawValue))</li>"
        }.joined(separator: "\n")
        return [
            "    <nav class=\"status-legend\" aria-label=\"Status legend\">",
            "      <ul>",
            items,
            "      </ul>",
            "    </nav>"
        ].joined(separator: "\n")
    }

    // MARK: - Project rollup (verdict + portfolio bands)

    /// The one derived project trajectory. Escalation is the strongest signal and dominates rework
    /// (feature decision D4); a present (non-suppressed) project velocity then co-derives the result
    /// (decision `velocity-feeds-trajectory`), and a suppressed velocity falls back to the
    /// escalation/rework-only signal unchanged.
    public enum DashboardTrajectory: String, Equatable, Sendable {
        case onTrack = "on track"
        case slipping
        case stalled
    }

    /// Derive the project trajectory from the aggregated section rows ONLY (no velocity, no wall
    /// clock): `stalled` when any node is escalated, else `slipping` when any node is in rework, else
    /// `on track`. This is the escalation/rework-only fallback the velocity-aware overload defers to
    /// when velocity is suppressed; kept as a public entry point so existing callers stay source-stable.
    public static func dashboardTrajectory(for sections: [DashboardSection]) -> DashboardTrajectory {
        let statuses = sections.flatMap(\.projection.rows).map(\.status)
        if statuses.contains(.escalated) { return .stalled }
        if statuses.contains(.rework) { return .slipping }
        return .onTrack
    }

    /// The velocity-aware trajectory (decision `velocity-feeds-trajectory`). Escalation→rework keep
    /// strict precedence (escalation ⇒ `stalled`, rework ⇒ `slipping`); only when neither fires does a
    /// PRESENT project velocity co-derive the verdict: zero completions in the trailing window ⇒
    /// `slipping` (movement stalled), a positive count ⇒ `on track`. When velocity is SUPPRESSED
    /// (no timestamped completion to count — thin/legacy history) the result equals the row-only
    /// `dashboardTrajectory(for:)` unchanged. Pure: `now` is injected; no wall clock is read.
    public static func dashboardTrajectory(for sections: [DashboardSection], now: Date) -> DashboardTrajectory {
        let base = dashboardTrajectory(for: sections)
        // Escalation/rework dominate velocity, so only refine the otherwise-clean `on track` verdict.
        guard base == .onTrack else { return base }
        guard let velocity = projectVelocity(for: sections, now: now) else { return base }
        return velocity > 0 ? .onTrack : .slipping
    }

    /// The feature-level project velocity for the verdict band: the sum of each section's
    /// (non-suppressed) trailing-window completion count, computed purely from the threaded
    /// `runEvents` against the injected `now`. Returns nil — SUPPRESSED — when NO section has a single
    /// timestamped completion to count (thin/legacy history), so the verdict band renders `—` rather
    /// than a false `0` (decision `self-suppression-rule`).
    static func projectVelocity(for sections: [DashboardSection], now: Date) -> Int? {
        var total = 0
        var anyPresent = false
        for section in sections {
            if let velocity = TemporalMetrics.metrics(from: section.runEvents, now: now).velocity {
                total += velocity
                anyPresent = true
            }
        }
        return anyPresent ? total : nil
    }

    /// One portfolio health row, derived purely from a section: status headline, slice-count %
    /// (labelled `slices`, not effort), owner (with `unowned` fallback), and the current blocker.
    public struct PortfolioRow: Equatable, Sendable {
        public var heading: String
        public var doneCount: Int
        public var totalCount: Int
        public var owner: String
        public var blocker: String
        public init(heading: String, doneCount: Int, totalCount: Int, owner: String, blocker: String) {
            self.heading = heading
            self.doneCount = doneCount
            self.totalCount = totalCount
            self.owner = owner
            self.blocker = blocker
        }
    }

    /// Derive one portfolio health row per section (pure, no I/O): the section summary supplies the
    /// `slices` count, the section's representative owner surfaces through the already-projected
    /// `row.owner` (falling back to the literal `unowned` when none is genuinely declared), and the
    /// current blocker is the worst escalated/rework node (or `—` when clear).
    public static func portfolioRows(for sections: [DashboardSection]) -> [PortfolioRow] {
        sections.map { section in
            PortfolioRow(
                heading: section.heading,
                doneCount: section.projection.summary.doneCount,
                totalCount: section.projection.summary.totalNodeCount,
                owner: portfolioOwner(for: section),
                blocker: portfolioBlocker(for: section))
        }
    }

    /// The integer slice-completion percent for a portfolio row (0 when a feature has no slices).
    static func slicePercent(done: Int, total: Int) -> Int {
        Int(progressPercent(done: done, total: total).rounded())
    }

    /// The representative owner for a feature's portfolio row. Reuses the owner already surfaced
    /// through `DashboardProjection.ownerLabel` on the section's rows; when no genuine owner is
    /// declared (the fallback degenerated to the feature/section name or empty), the cell renders the
    /// literal `unowned` so the gap is honest.
    private static func portfolioOwner(for section: DashboardSection) -> String {
        let owners = section.projection.rows.map(\.owner)
            .filter { !$0.isEmpty && $0 != featureName(of: section) }
        guard let owner = owners.first else { return "unowned" }
        return owner
    }

    /// The trailing segment of a section heading ("Feature · <name>" / "Program · <name>" /
    /// "Build pattern · <name>") — the feature name the owner fallback degenerates to.
    static func featureName(of section: DashboardSection) -> String {
        section.heading.split(separator: "·").last.map {
            $0.trimmingCharacters(in: .whitespaces)
        } ?? section.heading
    }

    private static func emptyStatusCounts() -> [DashboardStatus: Int] {
        Dictionary(uniqueKeysWithValues: DashboardStatus.allCases.map { ($0, 0) })
    }

    /// Owner-load groups for the "Load by owner" chart (answers *who is carrying how much*): every
    /// project slice bucketed by its owner, with untagged work — where the owner fallback degenerated
    /// to the feature/section name, or is empty — collapsed into a single honest `unowned` bucket
    /// (which shrinks as owners are assigned). `unowned` sorts last; real owners sort alphabetically.
    static func ownerLoadGroups(for sections: [DashboardSection]) -> [DashboardCharts.BarGroup] {
        var counts: [String: [DashboardStatus: Int]] = [:]
        for section in sections {
            let feature = featureName(of: section)
            for row in section.projection.rows {
                let owner = (row.owner.isEmpty || row.owner == feature) ? "unowned" : row.owner
                counts[owner, default: emptyStatusCounts()][row.status, default: 0] += 1
            }
        }
        let keys = counts.keys.sorted { a, b in
            if a == "unowned" { return false }
            if b == "unowned" { return true }
            return a < b
        }
        return keys.map { DashboardCharts.BarGroup(label: $0, counts: counts[$0] ?? emptyStatusCounts()) }
    }

    /// Feature-progress groups for the "Progress by feature" chart (answers *how far along is each
    /// feature/program*): one status-stacked bar per section, in assembled order. Distinct from the
    /// owner-load chart so each section has a single, unambiguous purpose.
    static func featureProgressGroups(for sections: [DashboardSection]) -> [DashboardCharts.BarGroup] {
        sections.map { section in
            var counts = emptyStatusCounts()
            for row in section.projection.rows { counts[row.status, default: 0] += 1 }
            return DashboardCharts.BarGroup(label: featureName(of: section), counts: counts)
        }
    }

    /// The current blocker for a feature's portfolio row: the first escalated node, else the first
    /// rework node, else `—`. Mirrors the trajectory precedence (escalation dominates).
    private static func portfolioBlocker(for section: DashboardSection) -> String {
        let rows = section.projection.rows
        if let escalated = rows.first(where: { $0.status == .escalated }) { return escalated.node }
        if let rework = rows.first(where: { $0.status == .rework }) { return rework.node }
        return "—"
    }

    // MARK: - Attention band (triage)

    /// The kind of triage item an attention entry represents, in rendering precedence: escalations and
    /// rework loops are on-fire (shown in full), top unblockers are advisory (capped).
    public enum AttentionKind: String, Equatable, Sendable {
        case escalation
        case rework
        case unblocker
    }

    /// One triage item in the attention band: its kind, the feature it concerns (the section heading),
    /// and the slice id (a projection-row node or a ranked-runnable node). `unblockCount` is set only
    /// for unblockers (how many downstream slices it would free); it is 0 for escalations/rework.
    public struct AttentionItem: Equatable, Sendable {
        public var kind: AttentionKind
        public var feature: String
        public var slice: String
        public var unblockCount: Int
        public init(kind: AttentionKind, feature: String, slice: String, unblockCount: Int = 0) {
            self.kind = kind
            self.feature = feature
            self.slice = slice
            self.unblockCount = unblockCount
        }
    }

    /// At most this many unblockers are surfaced, keeping the band within the brief's 3–6 triage
    /// budget so escalations/rework (always shown in full) are not buried under a long runnable list.
    static let attentionUnblockerCap = 3

    /// Derive the attention-band items purely from the already-assembled sections (rows + threaded
    /// ranking) — no new data source, no wall clock. ESCALATIONS (status `.escalated`) and REWORK loops
    /// (status `.rework`) come from each section's projection rows and are listed in full, each naming
    /// its feature (section heading) and slice (`row.node`). TOP UNBLOCKERS come from S2's
    /// `runnableRanking` threaded onto the section: across all sections, runnables with
    /// `unblockCount > 0` are taken in that ranking's order (descending unblock count, then ascending
    /// id) and capped at `attentionUnblockerCap`. Identical inputs yield identical output.
    public static func attentionItems(for sections: [DashboardSection]) -> [AttentionItem] {
        var escalations: [AttentionItem] = []
        var rework: [AttentionItem] = []
        for section in sections {
            for row in section.projection.rows {
                switch row.status {
                case .escalated:
                    escalations.append(AttentionItem(kind: .escalation, feature: section.heading, slice: row.node))
                case .rework:
                    rework.append(AttentionItem(kind: .rework, feature: section.heading, slice: row.node))
                default:
                    break
                }
            }
        }
        // Flatten the per-section rankings, preserving each section's S2 order, then keep the global
        // descending-unblock / ascending-id order and cap. unblockCount == 0 unblocks nothing, so it is
        // not a notable unblocker (and is what keeps the empty state empty when runnables free nothing).
        let unblockers = sections
            .flatMap { section in
                section.runnableRanking
                    .filter { $0.unblockCount > 0 }
                    .map { AttentionItem(kind: .unblocker, feature: section.heading, slice: $0.node,
                                         unblockCount: $0.unblockCount) }
            }
            .sorted { lhs, rhs in
                if lhs.unblockCount != rhs.unblockCount { return lhs.unblockCount > rhs.unblockCount }
                return lhs.slice < rhs.slice
            }
            .prefix(attentionUnblockerCap)
        return escalations + rework + Array(unblockers)
    }

    /// Render the attention band as an HTML fragment from the assembled sections. Pure: it reads only
    /// the derived `attentionItems` (no I/O, no wall clock). Returns the EMPTY STRING when there is
    /// nothing to act on (no escalations, no rework, no qualifying unblockers) — no section element, no
    /// heading, no empty box — so a clean dashboard emits no attention-band markup at all.
    static func attentionBandHTML(sections: [DashboardSection]) -> String {
        let items = attentionItems(for: sections)
        guard !items.isEmpty else { return "" }
        let groups: [(AttentionKind, String)] = [
            (.escalation, "Escalations"),
            (.rework, "Rework loops"),
            (.unblocker, "Top unblockers")
        ]
        var lines = [
            "    <section class=\"attention-band\" aria-label=\"Attention\">",
            "      <h2>Attention</h2>"
        ]
        for (kind, title) in groups {
            let groupItems = items.filter { $0.kind == kind }
            guard !groupItems.isEmpty else { continue }
            lines.append("      <div class=\"attention-group attention-\(kind.rawValue)\">")
            lines.append("        <h3>\(escapeHTML(title))</h3>")
            lines.append("        <ul>")
            for item in groupItems {
                let suffix = kind == .unblocker
                    ? " <span class=\"attention-unblock-count\">(unblocks \(item.unblockCount))</span>"
                    : ""
                lines.append("          <li><span class=\"attention-slice\">\(escapeHTML(item.slice))</span> <span class=\"attention-feature\">\(escapeHTML(item.feature))</span>\(suffix)</li>")
            }
            lines.append("        </ul>")
            lines.append("      </div>")
        }
        lines.append("    </section>")
        return lines.joined(separator: "\n")
    }

    /// The whole-project rollup: a verdict band (trajectory + generation timestamp + freshness badge),
    /// the attention/triage band (escalations, rework, top unblockers — or nothing when clear), and a
    /// portfolio band (one health row per feature), rendered before any per-feature detail.
    private static func projectRollupHTML(sections: [DashboardSection], now: Date) -> String {
        // Velocity co-derives the trajectory (replacing S1's deferred placeholder); a suppressed
        // velocity falls back to the escalation/rework-only signal unchanged.
        let trajectory = dashboardTrajectory(for: sections, now: now)
        let stale = sections.contains { $0.staleRun }
        // The freshness badge REUSES run-integrity's `⚠ stale run` marker — the single trust
        // mechanism — lit when any attached run is stale, and otherwise omitted.
        let freshnessBadge = stale
            ? "<span class=\"verdict-freshness stale\">\(escapeHTML("⚠ stale run"))</span>"
            : "<span class=\"verdict-freshness fresh\">fresh</span>"
        let verdict = [
            "    <section class=\"verdict-band\" aria-label=\"Project verdict\">",
            "      <span class=\"verdict-kicker\">verdict</span>",
            "      <p class=\"verdict-trajectory trajectory-\(trajectoryClass(trajectory))\">\(escapeHTML(trajectory.rawValue))</p>",
            temporalMetricsHTML(sections: sections, now: now),
            "      <p class=\"verdict-meta\">",
            "        <span class=\"verdict-generated\">generated \(escapeHTML(formatTimestamp(now)))</span>",
            "        \(freshnessBadge)",
            "      </p>",
            "    </section>"
        ].joined(separator: "\n")

        let rows = portfolioRows(for: sections).map { row in
            let percent = slicePercent(done: row.doneCount, total: row.totalCount)
            return [
                "          <tr>",
                "            <td>\(escapeHTML(row.heading))</td>",
                "            <td>\(row.doneCount)/\(row.totalCount) (\(percent)%) slices</td>",
                "            <td>\(escapeHTML(row.owner))</td>",
                "            <td>\(escapeHTML(row.blocker))</td>",
                "          </tr>"
            ].joined(separator: "\n")
        }.joined(separator: "\n")
        let portfolioBody = rows.isEmpty ? "          <tr><td colspan=\"4\">No features</td></tr>" : rows
        let portfolio = [
            "    <section class=\"portfolio-band\" aria-label=\"Portfolio health\">",
            "      <h2>Portfolio</h2>",
            "      <table class=\"portfolio-table\">",
            "        <thead>",
            "          <tr><th>Feature</th><th>Slices</th><th>Owner</th><th>Blocker</th></tr>",
            "        </thead>",
            "        <tbody>",
            portfolioBody,
            "        </tbody>",
            "      </table>",
            "    </section>"
        ].joined(separator: "\n")

        // Order: verdict, then the triage band (appended only when non-empty, so a clean dashboard
        // shows no attention markup), then portfolio.
        let attention = attentionBandHTML(sections: sections)
        return [verdict, attention, portfolio]
            .filter { !$0.isEmpty }
            .joined(separator: "\n")
    }

    /// The time-axis metrics block in the verdict band: the feature-level VELOCITY (completions in the
    /// trailing window), then per-slice CYCLE TIME and WIP AGE — each rendered as `—` when SUPPRESSED
    /// (its timestamped inputs are absent), never as a false `0`. Pure: reads only the threaded
    /// `runEvents` and the injected `now` (no wall clock, no store). The renderer stays a pure
    /// derivation — `TemporalMetrics` does the computation.
    static func temporalMetricsHTML(sections: [DashboardSection], now: Date) -> String {
        let velocity = projectVelocity(for: sections, now: now)
        let velocityText = velocity.map { "\($0) / 7d" } ?? "—"

        // Per-slice cycle time / WIP age, gathered across sections in section + slice-id order so the
        // output is deterministic. Each section labels its slices by the section heading's feature.
        var sliceLines: [String] = []
        for section in sections {
            let metrics = TemporalMetrics.metrics(from: section.runEvents, now: now)
            for slice in metrics.slices.keys.sorted() {
                guard let timing = metrics.slices[slice] else { continue }
                let cycle = timing.cycleTime.map(formatDuration) ?? "—"
                let wip = timing.wipAge.map(formatDuration) ?? "—"
                let agingClass = timing.aging ? " temporal-aging" : ""
                sliceLines.append([
                    "          <li class=\"temporal-slice\(agingClass)\">",
                    "            <span class=\"temporal-slice-id\">\(escapeHTML(slice))</span>",
                    "            <span class=\"temporal-cycle\">cycle \(escapeHTML(cycle))</span>",
                    "            <span class=\"temporal-wip\">wip \(escapeHTML(wip))</span>",
                    "          </li>"
                ].joined(separator: "\n"))
            }
        }
        let sliceBlock = sliceLines.isEmpty
            ? ""
            : "\n        <ul class=\"temporal-slices\">\n\(sliceLines.joined(separator: "\n"))\n        </ul>"

        return [
            "      <div class=\"verdict-temporal\" aria-label=\"Temporal metrics\">",
            "        <span class=\"temporal-velocity\">velocity \(escapeHTML(velocityText))</span>\(sliceBlock)",
            etaBandHTML(sections: sections, velocity: velocity),
            burndownHTML(sections: sections, now: now),
            whatsChangedHTML(sections: sections, now: now),
            "      </div>"
        ].joined(separator: "\n")
    }

    /// The "what changed since T-7d" block: replays every section's `runEvents` to the cutoff
    /// (`now − whatsChangedWindow`) and diffs against the present, listing what COMPLETED, what is
    /// NEWLY BLOCKED, and what is NEWLY ESCALATED. ALWAYS present — when the diff is the explicit
    /// no-change state (an empty window, or a legacy run with no parseable `at`) it prints one explicit
    /// "no change since 7d" line, mirroring the burndown block's always-present empty state, so an
    /// empty window is an explicit state rather than absent markup. Pure: reads only the threaded
    /// `runEvents` and the injected `now`; `TemporalMetrics` does the computation.
    static func whatsChangedHTML(sections: [DashboardSection], now: Date) -> String {
        // Aggregate every section's records (the project-tier "what changed" spans the whole portfolio,
        // exactly like burndown), then diff against the injected `now`.
        let records = sections.flatMap { $0.runEvents }
        let diff = TemporalMetrics.whatsChanged(from: records, now: now)

        let body: String
        if diff.isEmpty {
            body = "        <p class=\"whats-changed-empty\">no change since 7d</p>"
        } else {
            body = [
                whatsChangedList(label: "completed", cssClass: "whats-changed-completed",
                                 ids: diff.completed),
                whatsChangedList(label: "newly blocked", cssClass: "whats-changed-blocked",
                                 ids: diff.newlyBlocked),
                whatsChangedList(label: "newly escalated", cssClass: "whats-changed-escalated",
                                 ids: diff.newlyEscalated)
            ].filter { !$0.isEmpty }.joined(separator: "\n")
        }

        return [
            "      <div class=\"temporal-whats-changed\" aria-label=\"What changed since 7d\">",
            "        <span class=\"whats-changed-caption\">what changed · 7d</span>",
            body,
            "      </div>"
        ].joined(separator: "\n")
    }

    /// One labelled `<ul>` of changed ids, or `""` when the list is empty (so an empty category emits
    /// no markup, while the always-present no-change line is handled by the caller). Ids are escaped.
    private static func whatsChangedList(label: String, cssClass: String, ids: [String]) -> String {
        guard !ids.isEmpty else { return "" }
        let items = ids.map { "          <li>\(escapeHTML($0))</li>" }.joined(separator: "\n")
        return [
            "        <div class=\"\(cssClass)\">",
            "          <span class=\"whats-changed-label\">\(escapeHTML(label))</span>",
            "          <ul class=\"whats-changed-list\">",
            items,
            "          </ul>",
            "        </div>"
        ].joined(separator: "\n")
    }

    /// The burndown trajectory block: the cumulative-slices-done series (replayed from every section's
    /// `runEvents` against the injected `now`) rendered as a self-contained inline-SVG chart. When the
    /// series self-suppresses (no timestamped completion across any section) the chart renders its own
    /// empty state, so this block is always present and the chart speaks for itself. Pure: reads only
    /// the threaded `runEvents` and `now`.
    static func burndownHTML(sections: [DashboardSection], now: Date) -> String {
        // Aggregate every section's completion records into one series (project-tier burndown spans
        // the whole portfolio's timestamped completions), then replay against the injected `now`.
        let records = sections.flatMap { $0.runEvents }
        let series = TemporalMetrics.burndown(from: records, now: now)
        return [
            "        <figure class=\"temporal-burndown\">",
            "          <figcaption class=\"temporal-burndown-caption\">burndown</figcaption>",
            "          \(DashboardCharts.burndownChart(series))",
            "        </figure>"
        ].joined(separator: "\n")
    }

    /// The ETA band block: `remaining ÷ velocity` widened into a low/high RANGE with a confidence
    /// label, or a `—` "insufficient history" note when SUPPRESSED (velocity nil/0 or nothing
    /// remaining). NEVER a single date — only a range or the suppression note. `remaining` is the
    /// pending+runnable rows across all sections; `velocity` is the already-computed project velocity.
    /// The span is labelled relative to the trailing window (e.g. "~2.4–5.6 wk") — a relative duration,
    /// not an absolute completion instant. Pure: reads the projection rows + velocity, no wall clock.
    static func etaBandHTML(sections: [DashboardSection], velocity: Int?) -> String {
        let remaining = sections.reduce(0) { $0 + TemporalMetrics.remainingCount($1.projection.rows) }
        let estimate = TemporalMetrics.etaBand(velocity: velocity, remaining: remaining)
        let body: String
        switch estimate {
        case .suppressed:
            body = "<span class=\"eta-note eta-suppressed\">eta — (insufficient history)</span>"
        case let .band(low, high, confidence):
            let lowText = formatWindows(low)
            let highText = formatWindows(high)
            body = "<span class=\"eta-band\">eta \(escapeHTML(lowText))–\(escapeHTML(highText)) <span class=\"eta-confidence\">(\(escapeHTML(confidence.rawValue)) confidence)</span></span>"
        }
        return "        <div class=\"temporal-eta\" aria-label=\"ETA band\">\(body)</div>"
    }

    /// A compact relative-span label for an ETA bound expressed in trailing-velocity windows. Converts
    /// windows → days via `TemporalMetrics.velocityWindow` and prints the largest sensible unit
    /// (weeks, then days), so a band reads e.g. `~2.4 wk` — a relative duration, never an absolute
    /// date. Pure / deterministic: no locale or wall-clock read.
    static func formatWindows(_ windows: Double) -> String {
        let days = windows * (TemporalMetrics.velocityWindow / 86_400)
        if days >= 7 {
            return "~\(roundedOneDecimal(days / 7)) wk"
        }
        return "~\(roundedOneDecimal(days)) d"
    }

    /// Round a non-negative Double to one decimal place as a stable string (no locale), e.g. `2.4`.
    private static func roundedOneDecimal(_ value: Double) -> String {
        let scaled = (value * 10).rounded()
        let whole = Int(scaled) / 10
        let frac = Int(scaled) % 10
        return "\(whole).\(frac)"
    }

    /// A compact, deterministic human duration for a temporal metric (cycle time / WIP age): the
    /// largest sensible unit — days, then hours, then minutes, then seconds — with no locale or
    /// wall-clock read, so the same interval always renders byte-identically. A negative interval is
    /// clamped to `0s` (a backwards pair is a data glitch, not a negative duration).
    static func formatDuration(_ interval: TimeInterval) -> String {
        let seconds = max(0, Int(interval.rounded()))
        if seconds >= 86_400 { return "\(seconds / 86_400)d \((seconds % 86_400) / 3_600)h" }
        if seconds >= 3_600 { return "\(seconds / 3_600)h \((seconds % 3_600) / 60)m" }
        if seconds >= 60 { return "\(seconds / 60)m \(seconds % 60)s" }
        return "\(seconds)s"
    }

    private static func trajectoryClass(_ trajectory: DashboardTrajectory) -> String {
        switch trajectory {
        case .onTrack: return "on-track"
        case .slipping: return "slipping"
        case .stalled: return "stalled"
        }
    }

    /// A deterministic UTC timestamp for the verdict band, formatted purely from the injected `now`
    /// (no locale/time-zone wall-clock reads), so the same `now` always renders byte-identically.
    static func formatTimestamp(_ now: Date) -> String {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(identifier: "UTC") ?? .gmt
        let c = calendar.dateComponents([.year, .month, .day, .hour, .minute], from: now)
        return String(format: "%04d-%02d-%02d %02d:%02d UTC",
                      c.year ?? 0, c.month ?? 0, c.day ?? 0, c.hour ?? 0, c.minute ?? 0)
    }

    private static func sectionHTML(_ section: DashboardSection) -> String {
        // A best-effort-attached (stale) run gets a single `⚠ stale run` marker in the header,
        // HTML-escaped like the heading. A healthy/healed exact-path match carries no marker.
        let staleMarker = section.staleRun
            ? "<span class=\"stale-run-marker\">\(escapeHTML("⚠ stale run"))</span>"
            : ""
        var parts = [
            "    <section class=\"dashboard-section\">",
            "      <header>",
            "        <h2>\(escapeHTML(section.heading))\(staleMarker)</h2>",
            "        <p>\(section.projection.summary.doneCount)/\(section.projection.summary.totalNodeCount) done</p>",
            "      </header>"
        ]
        // The master-requirements DEFINITION (the feature's `## Goal`) pairs the "why" with the
        // graph's "what depends on what", rendered above the graph when present. Absent (nil) ⇒ the
        // pane is omitted and the graph still renders (graceful degradation).
        if let definition = definitionPaneHTML(section.requirementsDefinition) {
            parts.append(definition)
        }
        if let mermaid = section.mermaid {
            parts.append(mermaidHTML(mermaid))
        } else {
            parts.append(graphHTML(rows: section.projection.rows, criticalPath: section.criticalPathNodes))
        }
        parts += [
            tableHTML(rows: section.projection.rows),
            "    </section>"
        ]
        return parts.joined(separator: "\n")
    }

    private static func mermaidHTML(_ mermaid: String) -> String {
        [
            "      <div class=\"dashboard-mermaid-wrap\" aria-label=\"Dependency graph\">",
            "        <pre class=\"mermaid dashboard-mermaid\">",
            escapeHTML(mermaid),
            "        </pre>",
            "      </div>"
        ].joined(separator: "\n")
    }

    /// The definition pane: the feature's `## Goal` body rendered above its graph. Returns nil when
    /// the threaded definition is nil OR trims to empty, so a feature with no extractable Goal omits
    /// the pane entirely (graceful degradation) rather than rendering an empty box.
    private static func definitionPaneHTML(_ definition: String?) -> String? {
        guard let definition,
              !definition.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        let trimmed = definition.trimmingCharacters(in: .whitespacesAndNewlines)
        return [
            "      <section class=\"definition-pane\" aria-label=\"Requirements definition\">",
            "        <h3>Definition</h3>",
            "        <p>\(escapeHTML(trimmed))</p>",
            "      </section>"
        ].joined(separator: "\n")
    }

    /// `criticalPath` is the threaded set of critical-path node ids; nodes in it get an extra
    /// `critical-path` class + a `data-critical-path` flag so the longest dependency chain is marked
    /// in the HTML fallback exactly as it is in the mermaid graph. Defaulted to `[]` ⇒ marks nothing.
    private static func graphHTML(rows: [DashboardProjectionRow],
                                  criticalPath: Set<String> = []) -> String {
        let nodes = rows.map { row in
            let onCritical = criticalPath.contains(row.node)
            let criticalClass = onCritical ? " critical-path" : ""
            let criticalAttr = onCritical ? " data-critical-path=\"true\"" : ""
            return [
                "          <li class=\"dashboard-node status-\(escapeHTML(row.status.rawValue))\(criticalClass)\" data-status=\"\(escapeHTML(row.status.rawValue))\"\(criticalAttr)>",
                "            <span class=\"node-id\">\(escapeHTML(row.node))</span>",
                "            <span class=\"node-status\">\(escapeHTML(row.status.rawValue))</span>",
                "          </li>"
            ].joined(separator: "\n")
        }.joined(separator: "\n")

        let edges = graphEdges(rows: rows).map { edge in
            "          <li><span>\(escapeHTML(edge.from))</span><span aria-hidden=\"true\">→</span><span>\(escapeHTML(edge.to))</span></li>"
        }.joined(separator: "\n")
        let edgeContent = edges.isEmpty ? "          <li>No dependencies</li>" : edges

        return [
            "      <div class=\"dashboard-graph\" aria-label=\"Section graph\">",
            "        <ol class=\"dashboard-nodes\">",
            nodes,
            "        </ol>",
            "        <ul class=\"dashboard-edges\">",
            edgeContent,
            "        </ul>",
            "      </div>"
        ].joined(separator: "\n")
    }

    private static func tableHTML(rows: [DashboardProjectionRow]) -> String {
        let body = rows.map { row in
            [
                "          <tr class=\"status-\(escapeHTML(row.status.rawValue))\">",
                "            <td>\(escapeHTML(row.node))</td>",
                "            <td>\(escapeHTML(row.status.rawValue))</td>",
                "            <td>\(escapeHTML(row.owner))</td>",
                "            <td>\(escapeHTML(row.stack ?? "—"))</td>",
                "            <td>\(escapeHTML(row.lane ?? "—"))</td>",
                "            <td>\(escapeHTML(row.milestone ?? "—"))</td>",
                "            <td>\(max(0, row.dependencyCount))</td>",
                "            <td>\(escapeHTML(row.nextActionHint.rawValue))</td>",
                "          </tr>"
            ].joined(separator: "\n")
        }.joined(separator: "\n")
        let rowsHTML = body.isEmpty ? "          <tr><td colspan=\"8\">No slices</td></tr>" : body

        return [
            "      <table class=\"slice-table\">",
            "        <thead>",
            "          <tr><th>Node</th><th>Status</th><th>Owner</th><th>Stack</th><th>Lane</th><th>Milestone</th><th>Dependencies</th><th>Next action</th></tr>",
            "        </thead>",
            "        <tbody>",
            rowsHTML,
            "        </tbody>",
            "      </table>"
        ].joined(separator: "\n")
    }

    private static func graphEdges(rows: [DashboardProjectionRow]) -> [(from: String, to: String)] {
        rows.enumerated().flatMap { index, row -> [(from: String, to: String)] in
            guard row.dependencyCount > 0, index > 0 else { return [] }
            let first = max(0, index - row.dependencyCount)
            return rows[first..<index].map { ($0.node, row.node) }
        }
    }

    private static func dashboardStyles() -> String {
        let variables = DashboardStatus.allCases.map { status in
            "    --status-\(status.rawValue): \(DashboardCharts.defaultColors[status] ?? "#9e9e9e");"
        }.joined(separator: "\n")
        return """
        <style>
        :root {
        \(variables)
          --text: #1f2328;
          --muted: #59636e;
          --line: #d0d7de;
          --panel: #f6f8fa;
          --background: #ffffff;
        }
        * { box-sizing: border-box; }
        body { margin: 0; background: var(--background); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.45; }
        .dashboard-page { max-width: 1180px; margin: 0 auto; padding: 32px 20px 48px; }
        .dashboard-header { border-bottom: 1px solid var(--line); padding-bottom: 24px; }
        .dashboard-kicker { color: var(--muted); font-size: 0.82rem; font-weight: 700; letter-spacing: 0; margin: 0 0 8px; text-transform: uppercase; }
        h1 { font-size: 2rem; margin: 0 0 20px; }
        h2 { font-size: 1.2rem; margin: 0; }
        .summary-grid { display: grid; gap: 12px; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); margin-bottom: 20px; }
        .summary-grid > div { border: 1px solid var(--line); border-radius: 8px; padding: 14px 16px; }
        .summary-value { display: block; font-size: 1.55rem; font-weight: 700; }
        .summary-label { color: var(--muted); font-size: 0.86rem; }
        .progress-wrap p { color: var(--muted); margin: 8px 0 0; }
        .progress-track { background: var(--panel); border: 1px solid var(--line); border-radius: 999px; height: 14px; overflow: hidden; }
        .progress-fill { background: var(--status-done); height: 100%; }
        .status-legend ul { display: flex; flex-wrap: wrap; gap: 10px 18px; justify-content: center; list-style: none; margin: 22px 0; padding: 0; }
        .status-legend li { align-items: center; color: var(--muted); display: flex; gap: 8px; font-size: 0.92rem; }
        .legend-swatch { border-radius: 999px; display: inline-block; height: 10px; width: 10px; }
        .dashboard-charts { align-items: start; display: grid; gap: 20px; grid-template-columns: minmax(0, 1fr); margin-bottom: 28px; }
        .dashboard-chart { max-width: 100%; }
        .dashboard-status-donut { justify-self: center; max-width: 360px; }
        .dashboard-grouped-bars { width: 100%; }
        .temporal-eta { color: var(--muted); font-size: 0.92rem; margin-top: 8px; }
        .eta-confidence { color: var(--muted); font-size: 0.82rem; }
        .eta-suppressed { color: var(--muted); }
        .temporal-burndown { margin: 10px 0 0; }
        .temporal-burndown-caption { color: var(--muted); font-size: 0.78rem; font-weight: 700; letter-spacing: 0.04em; margin-bottom: 4px; text-transform: uppercase; }
        .dashboard-burndown { width: 100%; max-width: 760px; }
        .burndown-axis-label { fill: var(--muted); font-size: 0.7rem; }
        .dashboard-section { border-top: 1px solid var(--line); padding: 26px 0; }
        .dashboard-section > header { align-items: baseline; display: flex; justify-content: space-between; gap: 16px; margin-bottom: 16px; }
        .dashboard-section > header p { color: var(--muted); margin: 0; }
        .stale-run-marker { color: var(--status-rework); font-size: 0.8rem; font-weight: 700; margin-left: 10px; white-space: nowrap; }
        .definition-pane { background: var(--panel); border: 1px solid var(--line); border-left: 4px solid #d97706; border-radius: 8px; margin-bottom: 16px; padding: 12px 16px; }
        .definition-pane h3 { color: var(--muted); font-size: 0.78rem; font-weight: 700; letter-spacing: 0.04em; margin: 0 0 6px; text-transform: uppercase; }
        .definition-pane p { margin: 0; white-space: pre-line; }
        .dashboard-node.critical-path { border-left-color: #d97706; box-shadow: inset 0 0 0 1px #d97706; }
        .verdict-band { border: 1px solid var(--line); border-radius: 8px; margin: 24px 0 18px; padding: 18px 20px; }
        .verdict-kicker { color: var(--muted); font-size: 0.78rem; font-weight: 700; letter-spacing: 0.04em; text-transform: uppercase; }
        .verdict-trajectory { font-size: 1.5rem; font-weight: 700; margin: 6px 0 10px; }
        .trajectory-on-track { color: var(--status-done); }
        .trajectory-slipping { color: var(--status-rework); }
        .trajectory-stalled { color: var(--status-escalated); }
        .verdict-meta { align-items: center; color: var(--muted); display: flex; flex-wrap: wrap; gap: 12px; margin: 0; }
        .verdict-freshness { font-size: 0.82rem; font-weight: 700; }
        .verdict-freshness.stale { color: var(--status-rework); }
        .verdict-freshness.fresh { color: var(--status-done); }
        .attention-band { border: 1px solid var(--line); border-radius: 8px; margin: 0 0 18px; padding: 16px 20px; }
        .attention-band h2 { margin: 0 0 12px; }
        .attention-band h3 { color: var(--muted); font-size: 0.78rem; font-weight: 700; letter-spacing: 0.04em; margin: 12px 0 6px; text-transform: uppercase; }
        .attention-band ul { list-style: none; margin: 0; padding: 0; }
        .attention-band li { align-items: baseline; display: flex; flex-wrap: wrap; gap: 8px; padding: 4px 0; }
        .attention-escalation h3 { color: var(--status-escalated); }
        .attention-rework h3 { color: var(--status-rework); }
        .attention-slice { font-weight: 700; }
        .attention-feature { color: var(--muted); font-size: 0.9rem; }
        .attention-unblock-count { color: var(--muted); font-size: 0.82rem; }
        .portfolio-band { margin: 0 0 28px; }
        .portfolio-band h2 { margin-bottom: 12px; }
        .portfolio-table { border-collapse: collapse; font-size: 0.92rem; width: 100%; }
        .portfolio-table th, .portfolio-table td { border-bottom: 1px solid var(--line); padding: 10px 8px; text-align: left; vertical-align: top; }
        .portfolio-table th { color: var(--muted); font-size: 0.78rem; text-transform: uppercase; }
        .dashboard-mermaid-wrap { background: var(--panel); border: 1px solid var(--line); border-radius: 8px; margin-bottom: 18px; overflow-x: auto; padding: 16px; }
        .dashboard-mermaid { margin: 0; min-width: 640px; text-align: center; }
        .dashboard-graph { display: grid; gap: 16px; grid-template-columns: minmax(0, 1fr) minmax(220px, 0.45fr); margin-bottom: 18px; }
        .dashboard-nodes { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); list-style: none; margin: 0; padding: 0; }
        .dashboard-node { border: 1px solid var(--line); border-left: 5px solid currentColor; border-radius: 8px; color: var(--muted); min-height: 70px; padding: 12px; }
        .node-id { color: var(--text); display: block; font-weight: 700; overflow-wrap: anywhere; }
        .node-status { display: block; font-size: 0.82rem; margin-top: 6px; }
        .dashboard-edges { background: var(--panel); border-radius: 8px; list-style: none; margin: 0; padding: 12px; }
        .dashboard-edges li { align-items: center; display: flex; gap: 8px; min-height: 26px; overflow-wrap: anywhere; }
        .slice-table { border-collapse: collapse; font-size: 0.92rem; width: 100%; }
        .slice-table th, .slice-table td { border-bottom: 1px solid var(--line); padding: 10px 8px; text-align: left; vertical-align: top; }
        .slice-table th { color: var(--muted); font-size: 0.78rem; text-transform: uppercase; }
        .status-done { color: var(--status-done); }
        .status-in-progress { color: var(--status-in-progress); }
        .status-rework { color: var(--status-rework); }
        .status-escalated { color: var(--status-escalated); }
        .status-runnable { color: var(--status-runnable); }
        .status-pending { color: var(--status-pending); }
        .legend-swatch.status-done { background: var(--status-done); }
        .legend-swatch.status-in-progress { background: var(--status-in-progress); }
        .legend-swatch.status-rework { background: var(--status-rework); }
        .legend-swatch.status-escalated { background: var(--status-escalated); }
        .legend-swatch.status-runnable { background: var(--status-runnable); }
        .legend-swatch.status-pending { background: var(--status-pending); }
        @media (max-width: 760px) {
          .dashboard-graph { grid-template-columns: 1fr; }
          .slice-table { display: block; overflow-x: auto; }
        }
        </style>
        """
    }

    private static func mermaidScript() -> String {
        [
            "    <script type=\"module\">",
            "      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';",
            "      mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });",
            "      await mermaid.run({ querySelector: '.dashboard-mermaid' });",
            "    </script>"
        ].joined(separator: "\n")
    }

    /// The escaped inner label content (id + a detail line), without the node-shape brackets — so a
    /// caller can wrap it in `["…"]` (feature/plain) or `{{"…"}}` (milestone gate). Every dynamic
    /// value is escaped via `escapeMermaidLabel`.
    private static func dashboardLabelBody(_ node: PipelineNode, status: DashboardStatus,
                                           inheritedOwner: [String]) -> String {
        var detail = [status.rawValue]
        if let worker = node.worker, worker != node.id { detail.append(worker) }
        if node.pipeline != nil { detail.append("slice") }
        if let stack = node.stack { detail.append("[\(stack)]") }
        let owner = node.owner ?? (inheritedOwner.isEmpty ? nil : inheritedOwner)
        if let owner, !owner.isEmpty { detail.append("@\(owner.joined(separator: ","))") }
        return "\(escapeMermaidLabel(node.id))<br/>\(escapeMermaidLabel(detail.joined(separator: " ")))"
    }

    private static func mermaidClass(_ status: DashboardStatus) -> String {
        "status_\(status.rawValue.replacingOccurrences(of: "-", with: "_"))"
    }

    /// The dedicated milestone/gate class for a status (`milestone_<status>`), distinct from the
    /// feature/plain `status_<status>` class so a gate is styled as a gate while still color-keyed
    /// off its status (pass vs blocked).
    private static func milestoneClass(_ status: DashboardStatus) -> String {
        "milestone_\(status.rawValue.replacingOccurrences(of: "-", with: "_"))"
    }

    /// The dedicated critical-path mermaid class, layered over a node's status/milestone class via a
    /// SEPARATE `class <id,...> critical_path` statement (mermaid's multi-class form — a chained
    /// second `:::` is a grammar error) so the longest dependency chain reads while each node keeps
    /// its status color via its `:::status_*`/`:::milestone_*` shorthand.
    private static let criticalPathClass = "critical_path"

    private static func escapeMermaidLabel(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private static func escapeHTML(_ value: String) -> String {
        value
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }
}
