import Foundation
import AISDDModels

/// The pure schema→checks compiler (extracted from the `ai-sdd-compile-schema` skill prose into the
/// engine so it is one reusable, tested mechanism rather than per-run LLM judgement). It maps a
/// parsed `SchemaSpec` (+ its name/version) to the `CheckSpec(s)` it compiles to, each tagged by an
/// `Origin` recording whether it is mechanically derived (`autoGenerated`) or a human-authored
/// advisory marker (`authored`). The core does NO IO: it is keyed only off the schema's
/// name/version/format and its declared `rules`/`judge` — the CLI does file reads at the edges and a
/// separate render helper turns these into committed-shape YAML.
///
/// Three tiers (architecture.md §8):
///  - Tier-1 (`fields`): one `<name>.structure` deterministic check, `required: true`, command
///    `swift run ai-sdd check <schema-path> <artifact-path>`. This is the correctness anchor — it
///    MUST reproduce the committed `checks/<name>.structure.check.yaml`. Tagged `.autoGenerated`.
///  - Tier-2 (`rules`): an explicit-`command` rule compiles verbatim to a deterministic check
///    (`required` iff blocking), tagged `.autoGenerated`. An intent-only rule (no command) is an
///    advisory `.authored` marker — never a fabricated command.
///  - Tier-3 (`judge`): each judge is an advisory `.authored` marker (`checkKind: judge`,
///    `required: false`, no command) — never a fabricated verdict.
public enum SchemaCompiler {

    /// One compiled check: its committed check name, the `CheckSpec` it compiles to, the `Origin`
    /// that classifies it, and the repo-relative source path it would be committed at. Equatable so
    /// tests can assert the structural check equals the committed one field-for-field.
    public struct CompiledCheck: Equatable, Sendable {
        /// Whether a compiled check is mechanically derived from the schema (`autoGenerated`, safe to
        /// commit as-is) or an advisory marker a human must finish + eval-gate (`authored`).
        public enum Origin: String, Equatable, Sendable {
            case autoGenerated = "auto-generated"
            case authored
        }

        public var name: String
        public var spec: CheckSpec
        public var origin: Origin
        public var sourcePath: String

        public init(name: String, spec: CheckSpec, origin: Origin, sourcePath: String) {
            self.name = name
            self.spec = spec
            self.origin = origin
            self.sourcePath = sourcePath
        }
    }

    /// Compile a schema into its checks, in tier order (Tier-1 structural, then Tier-2 rules, then
    /// Tier-3 judges). `name`/`version` come from the schema envelope's metadata; `format` from the
    /// schema spec (defaulting to `yaml`, matching the committed schemas). Pure — no IO.
    public static func compile(_ schema: SchemaSpec, name: String, version: Int = 1) -> [CompiledCheck] {
        var checks: [CompiledCheck] = []
        if let structural = structuralCheck(schema, name: name, version: version) {
            checks.append(structural)
        }
        checks.append(contentsOf: ruleChecks(schema, name: name))
        checks.append(contentsOf: judgeChecks(schema, name: name))
        return checks
    }

    // MARK: - Tier 1: structural

    /// The Tier-1 structural check, keyed only off name/version/format (A2). Emitted when the schema
    /// declares any `fields` (a structured artifact the validator can gate). This is the committed
    /// reality `Drift` reconstructs and `ai-sdd check` runs.
    public static func structuralCheck(_ schema: SchemaSpec, name: String, version: Int = 1) -> CompiledCheck? {
        guard let fields = schema.fields, !fields.isEmpty else { return nil }
        let format = schema.format ?? "yaml"
        let schemaPath = Layout.schemaSourcePath(name: name)
        let artifactPath = Layout.artifactPath(name: name, version: version, format: format)
        let checkName = Layout.structuralCheckName(name: name)
        return CompiledCheck(
            name: checkName,
            spec: CheckSpec(
                checkKind: "deterministic",
                command: "swift run ai-sdd check \(schemaPath) \(artifactPath)",
                required: true),
            origin: .autoGenerated,
            sourcePath: Layout.checkSourcePath(checkName: checkName))
    }

    // MARK: - Tier 2: rules

    /// Compile each Tier-2 rule. An explicit-`command` rule → a verbatim deterministic check,
    /// `required` iff blocking, `.autoGenerated`. An intent-only rule (no command) → an advisory
    /// `.authored` marker carrying the intent in its `command`-less spec (never fabricated).
    private static func ruleChecks(_ schema: SchemaSpec, name: String) -> [CompiledCheck] {
        (schema.rules ?? []).map { rule in
            let checkName = "\(name).\(rule.id)"
            let sourcePath = Layout.checkSourcePath(checkName: checkName)
            if let command = rule.command {
                return CompiledCheck(
                    name: checkName,
                    spec: CheckSpec(checkKind: "deterministic", command: command, required: rule.isBlocking),
                    origin: .autoGenerated,
                    sourcePath: sourcePath)
            }
            // Intent-only: authored. No command is fabricated; it is advisory until a human maps it
            // to a trusted executor and eval-gates it.
            return CompiledCheck(
                name: checkName,
                spec: CheckSpec(checkKind: "deterministic", command: nil, required: false),
                origin: .authored,
                sourcePath: sourcePath)
        }
    }

    // MARK: - Tier 3: judges

    /// Compile each Tier-3 judge to an advisory `.authored` marker: `checkKind: judge`,
    /// `required: false`, no command and no verdict (A4).
    private static func judgeChecks(_ schema: SchemaSpec, name: String) -> [CompiledCheck] {
        (schema.judge ?? []).map { judge in
            let checkName = "\(name).\(judge.id)"
            return CompiledCheck(
                name: checkName,
                spec: CheckSpec(checkKind: "judge", command: nil, required: false),
                origin: .authored,
                sourcePath: Layout.checkSourcePath(checkName: checkName))
        }
    }
}
