import FactoryModels

/// Renders a Pipeline as a Mermaid flowchart — the "renders 1:1 to the DAG diagram" view (§5,
/// ADR-0027). Pure: a deterministic transform of spec data, no I/O and no LLM, so it is testable
/// without a run and reproducible. Works for both kinds of DAG — a build pattern (artifact edges,
/// labelled with the Schema) and an orchestration graph (`depends_on` edges, no label).
public enum GraphRenderer {
    /// A fenced Mermaid `flowchart` block for the pipeline. Every node is declared (so isolated
    /// nodes still appear and labels are controlled); each edge renders an arrow, carrying its
    /// artifact Schema as the edge label unless it is absent or the `*` wildcard.
    public static func mermaid(_ pipeline: PipelineSpec, direction: String = "TD",
                               inheritedOwner: [String] = []) -> String {
        var lines = ["```mermaid", "flowchart \(direction)"]
        for node in pipeline.nodes {
            lines.append("    \(safeID(node.id))\(label(node, inheritedOwner: inheritedOwner))")
        }
        for edge in pipeline.edges {
            let schema = edge.artifact.flatMap { $0 == "*" ? nil : $0 }
            let arrow = schema.map { "-->|\($0)|" } ?? "-->"
            for from in edge.from.values {
                lines.append("    \(safeID(from)) \(arrow) \(safeID(edge.to))")
            }
        }
        lines.append("```")
        return lines.joined(separator: "\n")
    }

    /// One section of a project index: a heading and a pre-rendered body (a Mermaid block, or a
    /// note when a pipeline could not be loaded).
    public struct Section: Equatable, Sendable {
        public var heading: String
        public var body: String
        public init(heading: String, body: String) { self.heading = heading; self.body = body }
    }

    /// Assemble a single "single place, then drill down" index Markdown: a table of contents over
    /// the sections (the build pattern + one per feature), then each section's graph. One file that
    /// renders in any Markdown viewer; the TOC anchors are the drill-down.
    public static func projectIndex(title: String, sections: [Section]) -> String {
        var lines = ["# \(title) — project graph", "",
                     "_Generated by `factory graph --project` (ADR-0027). One place; the contents links drill down._", ""]
        if sections.count > 1 {
            lines.append("## Contents")
            for section in sections { lines.append("- [\(section.heading)](#\(anchor(section.heading)))") }
            lines.append("")
        }
        for section in sections {
            lines.append("## \(section.heading)")
            lines.append("")
            lines.append(section.body)
            lines.append("")
        }
        return lines.joined(separator: "\n")
    }

    /// A GitHub-style heading anchor: lowercase, spaces → `-`, drop other punctuation.
    static func anchor(_ heading: String) -> String {
        var out = ""
        for ch in heading.lowercased() {
            if ch.isLetter || ch.isNumber { out.append(ch) }
            else if ch == " " || ch == "-" { out.append("-") }
        }
        return out
    }

    /// Mermaid node ids must be identifier-safe; non-identifier characters map to `_`. The original
    /// id is preserved in the visible label, so kebab-case ids read normally.
    private static func safeID(_ id: String) -> String {
        String(id.map { $0.isLetter || $0.isNumber || $0 == "_" ? $0 : "_" })
    }

    /// The visible node label: the id, plus a second line noting the worker, that it is a slice, its
    /// stack, and its owner — whatever the node declares (owner inherits the feature lead if unset).
    private static func label(_ node: PipelineNode, inheritedOwner: [String]) -> String {
        var detail: [String] = []
        if let worker = node.worker, worker != node.id { detail.append(worker) }   // skip if redundant
        if node.pipeline != nil { detail.append("slice") }
        if let stack = node.stack { detail.append("[\(stack)]") }
        let owner = node.owner ?? (inheritedOwner.isEmpty ? nil : inheritedOwner)
        if let owner, !owner.isEmpty { detail.append("@\(owner.joined(separator: ","))") }
        let second = detail.isEmpty ? "" : "<br/>\(detail.joined(separator: " "))"
        return "[\"\(node.id)\(second)\"]"
    }

    /// A one-line fragment header for the four tags (ADR-0027), or nil when none are set — so a plain
    /// pipeline renders unchanged. Goes above the graph in the rendered Markdown.
    public static func fragmentHeader(_ metadata: SpecMetadata) -> String? {
        var parts: [String] = []
        if let factory = metadata.factory { parts.append("**lane** \(factory)") }
        if let owner = metadata.owner, !owner.isEmpty { parts.append("**owner** \(owner.joined(separator: ", "))") }
        if let correlation = metadata.correlation { parts.append("**milestone** \(correlation)") }
        if let origin = metadata.origin, let text = originLabel(origin) { parts.append("**origin** \(text)") }
        return parts.isEmpty ? nil : parts.joined(separator: "  ·  ")
    }

    /// `repo@tag (hash) /path` — only the parts that are present.
    private static func originLabel(_ origin: Origin) -> String? {
        var text = origin.repo ?? ""
        if let tag = origin.tag { text += "@\(tag)" }
        if let hash = origin.hash { text += " (\(hash.prefix(8)))" }
        if let path = origin.path { text += text.isEmpty ? path : " \(path)" }
        let trimmed = text.trimmingCharacters(in: .whitespaces)
        return trimmed.isEmpty ? nil : trimmed
    }
}
