#!/usr/bin/env bash
#
# gen-embedded-resources.sh — pack the framework skills + the pre-commit hook into a generated
# Swift source compiled INTO the binary (no SwiftPM resource bundle).
#
# This is the embedded-resources analogue of gen-version.sh: it reads the repo-root sources of truth
# (skills/<id>/SKILL.md and hooks/pre-commit) and emits a gitignored generated Swift file that the
# AISDDEngine target compiles in, so a single relocated `ai-sdd` binary (no .build, no sibling bundle,
# no clone) can read every skill + the hook. Reading repo-root directly means there is no committed
# duplicate to drift (unlike the old Sources/AISDDEngine/Resources/ copies).
#
# Run it before `swift build` (install.sh and .github/workflows/release.yml wire it in, exactly as
# they wire gen-version.sh). The output is gitignored.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/Sources/AISDDEngine/Generated/EmbeddedFrameworkData.swift"
mkdir -p "$(dirname "$OUT")"

b64() { base64 < "$1" | tr -d '\n'; }   # single-line base64 (macOS wraps by default)

{
  echo "// Generated by scripts/gen-embedded-resources.sh — do not edit, do not commit."
  echo "// The framework skills + pre-commit hook, packed into the binary so a relocated lone"
  echo "// binary needs no sibling resource bundle. Source of truth: repo-root skills/ + hooks/."
  echo "enum EmbeddedFrameworkData {"
  echo "    /// (skill id, base64-encoded SKILL.md) — one per framework skill, id-sorted."
  echo "    static let skills: [(id: String, base64: String)] = ["
  for dir in "$ROOT"/skills/*/; do
    id="$(basename "$dir")"
    file="$dir/SKILL.md"
    [ -f "$file" ] || continue
    printf '        ("%s", "%s"),\n' "$id" "$(b64 "$file")"
  done
  echo "    ]"
  echo "    /// base64-encoded hooks/pre-commit source."
  printf '    static let preCommitHookBase64 = "%s"\n' "$(b64 "$ROOT/hooks/pre-commit")"
  echo "}"
} > "$OUT"

echo "generated $OUT ($(grep -c '^        (' "$OUT") skills + hook)"
