#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/Sources/AISDDCLI/Version.swift"
if VER="$(git -C "$ROOT" describe --tags --always --dirty 2>/dev/null)"; then
  VER="${VER#v}"                       # v0.6.0 → 0.6.0 (no-op on a bare SHA)
else
  VER="0.0.0-unknown"                  # not a git checkout (e.g. a source tarball)
fi
printf '// Generated by scripts/gen-version.sh — do not edit, do not commit.\nenum AISDDVersion { static let current = "%s" }\n' "$VER" > "$OUT"
